// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server/api/internal/v1/authority.proto

package internalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "watch_together/server/internal/rpcgen/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoomAuthorityInternalServiceName is the fully-qualified name of the RoomAuthorityInternalService
	// service.
	RoomAuthorityInternalServiceName = "watch_together.internal.v1.RoomAuthorityInternalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoomAuthorityInternalServiceGetRoomAuthorityProcedure is the fully-qualified name of the
	// RoomAuthorityInternalService's GetRoomAuthority RPC.
	RoomAuthorityInternalServiceGetRoomAuthorityProcedure = "/watch_together.internal.v1.RoomAuthorityInternalService/GetRoomAuthority"
	// RoomAuthorityInternalServiceClaimRoomAuthorityProcedure is the fully-qualified name of the
	// RoomAuthorityInternalService's ClaimRoomAuthority RPC.
	RoomAuthorityInternalServiceClaimRoomAuthorityProcedure = "/watch_together.internal.v1.RoomAuthorityInternalService/ClaimRoomAuthority"
	// RoomAuthorityInternalServiceRenewRoomAuthorityProcedure is the fully-qualified name of the
	// RoomAuthorityInternalService's RenewRoomAuthority RPC.
	RoomAuthorityInternalServiceRenewRoomAuthorityProcedure = "/watch_together.internal.v1.RoomAuthorityInternalService/RenewRoomAuthority"
	// RoomAuthorityInternalServiceBeginRoomRecoveryProcedure is the fully-qualified name of the
	// RoomAuthorityInternalService's BeginRoomRecovery RPC.
	RoomAuthorityInternalServiceBeginRoomRecoveryProcedure = "/watch_together.internal.v1.RoomAuthorityInternalService/BeginRoomRecovery"
	// RoomAuthorityInternalServiceCompleteRoomRecoveryProcedure is the fully-qualified name of the
	// RoomAuthorityInternalService's CompleteRoomRecovery RPC.
	RoomAuthorityInternalServiceCompleteRoomRecoveryProcedure = "/watch_together.internal.v1.RoomAuthorityInternalService/CompleteRoomRecovery"
	// RoomAuthorityInternalServiceApplyRoomControlProcedure is the fully-qualified name of the
	// RoomAuthorityInternalService's ApplyRoomControl RPC.
	RoomAuthorityInternalServiceApplyRoomControlProcedure = "/watch_together.internal.v1.RoomAuthorityInternalService/ApplyRoomControl"
)

// RoomAuthorityInternalServiceClient is a client for the
// watch_together.internal.v1.RoomAuthorityInternalService service.
type RoomAuthorityInternalServiceClient interface {
	GetRoomAuthority(context.Context, *connect.Request[v1.GetRoomAuthorityRequest]) (*connect.Response[v1.GetRoomAuthorityResponse], error)
	ClaimRoomAuthority(context.Context, *connect.Request[v1.ClaimRoomAuthorityRequest]) (*connect.Response[v1.ClaimRoomAuthorityResponse], error)
	RenewRoomAuthority(context.Context, *connect.Request[v1.RenewRoomAuthorityRequest]) (*connect.Response[v1.RenewRoomAuthorityResponse], error)
	BeginRoomRecovery(context.Context, *connect.Request[v1.BeginRoomRecoveryRequest]) (*connect.Response[v1.BeginRoomRecoveryResponse], error)
	CompleteRoomRecovery(context.Context, *connect.Request[v1.CompleteRoomRecoveryRequest]) (*connect.Response[v1.CompleteRoomRecoveryResponse], error)
	ApplyRoomControl(context.Context, *connect.Request[v1.ApplyRoomControlRequest]) (*connect.Response[v1.ApplyRoomControlResponse], error)
}

// NewRoomAuthorityInternalServiceClient constructs a client for the
// watch_together.internal.v1.RoomAuthorityInternalService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoomAuthorityInternalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoomAuthorityInternalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roomAuthorityInternalServiceMethods := v1.File_server_api_internal_v1_authority_proto.Services().ByName("RoomAuthorityInternalService").Methods()
	return &roomAuthorityInternalServiceClient{
		getRoomAuthority: connect.NewClient[v1.GetRoomAuthorityRequest, v1.GetRoomAuthorityResponse](
			httpClient,
			baseURL+RoomAuthorityInternalServiceGetRoomAuthorityProcedure,
			connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("GetRoomAuthority")),
			connect.WithClientOptions(opts...),
		),
		claimRoomAuthority: connect.NewClient[v1.ClaimRoomAuthorityRequest, v1.ClaimRoomAuthorityResponse](
			httpClient,
			baseURL+RoomAuthorityInternalServiceClaimRoomAuthorityProcedure,
			connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("ClaimRoomAuthority")),
			connect.WithClientOptions(opts...),
		),
		renewRoomAuthority: connect.NewClient[v1.RenewRoomAuthorityRequest, v1.RenewRoomAuthorityResponse](
			httpClient,
			baseURL+RoomAuthorityInternalServiceRenewRoomAuthorityProcedure,
			connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("RenewRoomAuthority")),
			connect.WithClientOptions(opts...),
		),
		beginRoomRecovery: connect.NewClient[v1.BeginRoomRecoveryRequest, v1.BeginRoomRecoveryResponse](
			httpClient,
			baseURL+RoomAuthorityInternalServiceBeginRoomRecoveryProcedure,
			connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("BeginRoomRecovery")),
			connect.WithClientOptions(opts...),
		),
		completeRoomRecovery: connect.NewClient[v1.CompleteRoomRecoveryRequest, v1.CompleteRoomRecoveryResponse](
			httpClient,
			baseURL+RoomAuthorityInternalServiceCompleteRoomRecoveryProcedure,
			connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("CompleteRoomRecovery")),
			connect.WithClientOptions(opts...),
		),
		applyRoomControl: connect.NewClient[v1.ApplyRoomControlRequest, v1.ApplyRoomControlResponse](
			httpClient,
			baseURL+RoomAuthorityInternalServiceApplyRoomControlProcedure,
			connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("ApplyRoomControl")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roomAuthorityInternalServiceClient implements RoomAuthorityInternalServiceClient.
type roomAuthorityInternalServiceClient struct {
	getRoomAuthority     *connect.Client[v1.GetRoomAuthorityRequest, v1.GetRoomAuthorityResponse]
	claimRoomAuthority   *connect.Client[v1.ClaimRoomAuthorityRequest, v1.ClaimRoomAuthorityResponse]
	renewRoomAuthority   *connect.Client[v1.RenewRoomAuthorityRequest, v1.RenewRoomAuthorityResponse]
	beginRoomRecovery    *connect.Client[v1.BeginRoomRecoveryRequest, v1.BeginRoomRecoveryResponse]
	completeRoomRecovery *connect.Client[v1.CompleteRoomRecoveryRequest, v1.CompleteRoomRecoveryResponse]
	applyRoomControl     *connect.Client[v1.ApplyRoomControlRequest, v1.ApplyRoomControlResponse]
}

// GetRoomAuthority calls watch_together.internal.v1.RoomAuthorityInternalService.GetRoomAuthority.
func (c *roomAuthorityInternalServiceClient) GetRoomAuthority(ctx context.Context, req *connect.Request[v1.GetRoomAuthorityRequest]) (*connect.Response[v1.GetRoomAuthorityResponse], error) {
	return c.getRoomAuthority.CallUnary(ctx, req)
}

// ClaimRoomAuthority calls
// watch_together.internal.v1.RoomAuthorityInternalService.ClaimRoomAuthority.
func (c *roomAuthorityInternalServiceClient) ClaimRoomAuthority(ctx context.Context, req *connect.Request[v1.ClaimRoomAuthorityRequest]) (*connect.Response[v1.ClaimRoomAuthorityResponse], error) {
	return c.claimRoomAuthority.CallUnary(ctx, req)
}

// RenewRoomAuthority calls
// watch_together.internal.v1.RoomAuthorityInternalService.RenewRoomAuthority.
func (c *roomAuthorityInternalServiceClient) RenewRoomAuthority(ctx context.Context, req *connect.Request[v1.RenewRoomAuthorityRequest]) (*connect.Response[v1.RenewRoomAuthorityResponse], error) {
	return c.renewRoomAuthority.CallUnary(ctx, req)
}

// BeginRoomRecovery calls
// watch_together.internal.v1.RoomAuthorityInternalService.BeginRoomRecovery.
func (c *roomAuthorityInternalServiceClient) BeginRoomRecovery(ctx context.Context, req *connect.Request[v1.BeginRoomRecoveryRequest]) (*connect.Response[v1.BeginRoomRecoveryResponse], error) {
	return c.beginRoomRecovery.CallUnary(ctx, req)
}

// CompleteRoomRecovery calls
// watch_together.internal.v1.RoomAuthorityInternalService.CompleteRoomRecovery.
func (c *roomAuthorityInternalServiceClient) CompleteRoomRecovery(ctx context.Context, req *connect.Request[v1.CompleteRoomRecoveryRequest]) (*connect.Response[v1.CompleteRoomRecoveryResponse], error) {
	return c.completeRoomRecovery.CallUnary(ctx, req)
}

// ApplyRoomControl calls watch_together.internal.v1.RoomAuthorityInternalService.ApplyRoomControl.
func (c *roomAuthorityInternalServiceClient) ApplyRoomControl(ctx context.Context, req *connect.Request[v1.ApplyRoomControlRequest]) (*connect.Response[v1.ApplyRoomControlResponse], error) {
	return c.applyRoomControl.CallUnary(ctx, req)
}

// RoomAuthorityInternalServiceHandler is an implementation of the
// watch_together.internal.v1.RoomAuthorityInternalService service.
type RoomAuthorityInternalServiceHandler interface {
	GetRoomAuthority(context.Context, *connect.Request[v1.GetRoomAuthorityRequest]) (*connect.Response[v1.GetRoomAuthorityResponse], error)
	ClaimRoomAuthority(context.Context, *connect.Request[v1.ClaimRoomAuthorityRequest]) (*connect.Response[v1.ClaimRoomAuthorityResponse], error)
	RenewRoomAuthority(context.Context, *connect.Request[v1.RenewRoomAuthorityRequest]) (*connect.Response[v1.RenewRoomAuthorityResponse], error)
	BeginRoomRecovery(context.Context, *connect.Request[v1.BeginRoomRecoveryRequest]) (*connect.Response[v1.BeginRoomRecoveryResponse], error)
	CompleteRoomRecovery(context.Context, *connect.Request[v1.CompleteRoomRecoveryRequest]) (*connect.Response[v1.CompleteRoomRecoveryResponse], error)
	ApplyRoomControl(context.Context, *connect.Request[v1.ApplyRoomControlRequest]) (*connect.Response[v1.ApplyRoomControlResponse], error)
}

// NewRoomAuthorityInternalServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoomAuthorityInternalServiceHandler(svc RoomAuthorityInternalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roomAuthorityInternalServiceMethods := v1.File_server_api_internal_v1_authority_proto.Services().ByName("RoomAuthorityInternalService").Methods()
	roomAuthorityInternalServiceGetRoomAuthorityHandler := connect.NewUnaryHandler(
		RoomAuthorityInternalServiceGetRoomAuthorityProcedure,
		svc.GetRoomAuthority,
		connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("GetRoomAuthority")),
		connect.WithHandlerOptions(opts...),
	)
	roomAuthorityInternalServiceClaimRoomAuthorityHandler := connect.NewUnaryHandler(
		RoomAuthorityInternalServiceClaimRoomAuthorityProcedure,
		svc.ClaimRoomAuthority,
		connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("ClaimRoomAuthority")),
		connect.WithHandlerOptions(opts...),
	)
	roomAuthorityInternalServiceRenewRoomAuthorityHandler := connect.NewUnaryHandler(
		RoomAuthorityInternalServiceRenewRoomAuthorityProcedure,
		svc.RenewRoomAuthority,
		connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("RenewRoomAuthority")),
		connect.WithHandlerOptions(opts...),
	)
	roomAuthorityInternalServiceBeginRoomRecoveryHandler := connect.NewUnaryHandler(
		RoomAuthorityInternalServiceBeginRoomRecoveryProcedure,
		svc.BeginRoomRecovery,
		connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("BeginRoomRecovery")),
		connect.WithHandlerOptions(opts...),
	)
	roomAuthorityInternalServiceCompleteRoomRecoveryHandler := connect.NewUnaryHandler(
		RoomAuthorityInternalServiceCompleteRoomRecoveryProcedure,
		svc.CompleteRoomRecovery,
		connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("CompleteRoomRecovery")),
		connect.WithHandlerOptions(opts...),
	)
	roomAuthorityInternalServiceApplyRoomControlHandler := connect.NewUnaryHandler(
		RoomAuthorityInternalServiceApplyRoomControlProcedure,
		svc.ApplyRoomControl,
		connect.WithSchema(roomAuthorityInternalServiceMethods.ByName("ApplyRoomControl")),
		connect.WithHandlerOptions(opts...),
	)
	return "/watch_together.internal.v1.RoomAuthorityInternalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoomAuthorityInternalServiceGetRoomAuthorityProcedure:
			roomAuthorityInternalServiceGetRoomAuthorityHandler.ServeHTTP(w, r)
		case RoomAuthorityInternalServiceClaimRoomAuthorityProcedure:
			roomAuthorityInternalServiceClaimRoomAuthorityHandler.ServeHTTP(w, r)
		case RoomAuthorityInternalServiceRenewRoomAuthorityProcedure:
			roomAuthorityInternalServiceRenewRoomAuthorityHandler.ServeHTTP(w, r)
		case RoomAuthorityInternalServiceBeginRoomRecoveryProcedure:
			roomAuthorityInternalServiceBeginRoomRecoveryHandler.ServeHTTP(w, r)
		case RoomAuthorityInternalServiceCompleteRoomRecoveryProcedure:
			roomAuthorityInternalServiceCompleteRoomRecoveryHandler.ServeHTTP(w, r)
		case RoomAuthorityInternalServiceApplyRoomControlProcedure:
			roomAuthorityInternalServiceApplyRoomControlHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoomAuthorityInternalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoomAuthorityInternalServiceHandler struct{}

func (UnimplementedRoomAuthorityInternalServiceHandler) GetRoomAuthority(context.Context, *connect.Request[v1.GetRoomAuthorityRequest]) (*connect.Response[v1.GetRoomAuthorityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomAuthorityInternalService.GetRoomAuthority is not implemented"))
}

func (UnimplementedRoomAuthorityInternalServiceHandler) ClaimRoomAuthority(context.Context, *connect.Request[v1.ClaimRoomAuthorityRequest]) (*connect.Response[v1.ClaimRoomAuthorityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomAuthorityInternalService.ClaimRoomAuthority is not implemented"))
}

func (UnimplementedRoomAuthorityInternalServiceHandler) RenewRoomAuthority(context.Context, *connect.Request[v1.RenewRoomAuthorityRequest]) (*connect.Response[v1.RenewRoomAuthorityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomAuthorityInternalService.RenewRoomAuthority is not implemented"))
}

func (UnimplementedRoomAuthorityInternalServiceHandler) BeginRoomRecovery(context.Context, *connect.Request[v1.BeginRoomRecoveryRequest]) (*connect.Response[v1.BeginRoomRecoveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomAuthorityInternalService.BeginRoomRecovery is not implemented"))
}

func (UnimplementedRoomAuthorityInternalServiceHandler) CompleteRoomRecovery(context.Context, *connect.Request[v1.CompleteRoomRecoveryRequest]) (*connect.Response[v1.CompleteRoomRecoveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomAuthorityInternalService.CompleteRoomRecovery is not implemented"))
}

func (UnimplementedRoomAuthorityInternalServiceHandler) ApplyRoomControl(context.Context, *connect.Request[v1.ApplyRoomControlRequest]) (*connect.Response[v1.ApplyRoomControlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomAuthorityInternalService.ApplyRoomControl is not implemented"))
}
