// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server/api/internal/v1/home.proto

package internalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "watch_together/server/internal/rpcgen/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HomeCompositionInternalServiceName is the fully-qualified name of the
	// HomeCompositionInternalService service.
	HomeCompositionInternalServiceName = "watch_together.internal.v1.HomeCompositionInternalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HomeCompositionInternalServiceGetHomeSummaryProcedure is the fully-qualified name of the
	// HomeCompositionInternalService's GetHomeSummary RPC.
	HomeCompositionInternalServiceGetHomeSummaryProcedure = "/watch_together.internal.v1.HomeCompositionInternalService/GetHomeSummary"
)

// HomeCompositionInternalServiceClient is a client for the
// watch_together.internal.v1.HomeCompositionInternalService service.
type HomeCompositionInternalServiceClient interface {
	GetHomeSummary(context.Context, *connect.Request[v1.GetHomeSummaryRequest]) (*connect.Response[v1.GetHomeSummaryResponse], error)
}

// NewHomeCompositionInternalServiceClient constructs a client for the
// watch_together.internal.v1.HomeCompositionInternalService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHomeCompositionInternalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HomeCompositionInternalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	homeCompositionInternalServiceMethods := v1.File_server_api_internal_v1_home_proto.Services().ByName("HomeCompositionInternalService").Methods()
	return &homeCompositionInternalServiceClient{
		getHomeSummary: connect.NewClient[v1.GetHomeSummaryRequest, v1.GetHomeSummaryResponse](
			httpClient,
			baseURL+HomeCompositionInternalServiceGetHomeSummaryProcedure,
			connect.WithSchema(homeCompositionInternalServiceMethods.ByName("GetHomeSummary")),
			connect.WithClientOptions(opts...),
		),
	}
}

// homeCompositionInternalServiceClient implements HomeCompositionInternalServiceClient.
type homeCompositionInternalServiceClient struct {
	getHomeSummary *connect.Client[v1.GetHomeSummaryRequest, v1.GetHomeSummaryResponse]
}

// GetHomeSummary calls watch_together.internal.v1.HomeCompositionInternalService.GetHomeSummary.
func (c *homeCompositionInternalServiceClient) GetHomeSummary(ctx context.Context, req *connect.Request[v1.GetHomeSummaryRequest]) (*connect.Response[v1.GetHomeSummaryResponse], error) {
	return c.getHomeSummary.CallUnary(ctx, req)
}

// HomeCompositionInternalServiceHandler is an implementation of the
// watch_together.internal.v1.HomeCompositionInternalService service.
type HomeCompositionInternalServiceHandler interface {
	GetHomeSummary(context.Context, *connect.Request[v1.GetHomeSummaryRequest]) (*connect.Response[v1.GetHomeSummaryResponse], error)
}

// NewHomeCompositionInternalServiceHandler builds an HTTP handler from the service implementation.
// It returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHomeCompositionInternalServiceHandler(svc HomeCompositionInternalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	homeCompositionInternalServiceMethods := v1.File_server_api_internal_v1_home_proto.Services().ByName("HomeCompositionInternalService").Methods()
	homeCompositionInternalServiceGetHomeSummaryHandler := connect.NewUnaryHandler(
		HomeCompositionInternalServiceGetHomeSummaryProcedure,
		svc.GetHomeSummary,
		connect.WithSchema(homeCompositionInternalServiceMethods.ByName("GetHomeSummary")),
		connect.WithHandlerOptions(opts...),
	)
	return "/watch_together.internal.v1.HomeCompositionInternalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HomeCompositionInternalServiceGetHomeSummaryProcedure:
			homeCompositionInternalServiceGetHomeSummaryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHomeCompositionInternalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHomeCompositionInternalServiceHandler struct{}

func (UnimplementedHomeCompositionInternalServiceHandler) GetHomeSummary(context.Context, *connect.Request[v1.GetHomeSummaryRequest]) (*connect.Response[v1.GetHomeSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.HomeCompositionInternalService.GetHomeSummary is not implemented"))
}
