// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server/api/internal/v1/identity.proto

package internalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "watch_together/server/internal/rpcgen/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityInternalServiceName is the fully-qualified name of the IdentityInternalService service.
	IdentityInternalServiceName = "watch_together.internal.v1.IdentityInternalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityInternalServiceRegisterProcedure is the fully-qualified name of the
	// IdentityInternalService's Register RPC.
	IdentityInternalServiceRegisterProcedure = "/watch_together.internal.v1.IdentityInternalService/Register"
	// IdentityInternalServiceLoginProcedure is the fully-qualified name of the
	// IdentityInternalService's Login RPC.
	IdentityInternalServiceLoginProcedure = "/watch_together.internal.v1.IdentityInternalService/Login"
	// IdentityInternalServiceVerifyAccessTokenProcedure is the fully-qualified name of the
	// IdentityInternalService's VerifyAccessToken RPC.
	IdentityInternalServiceVerifyAccessTokenProcedure = "/watch_together.internal.v1.IdentityInternalService/VerifyAccessToken"
	// IdentityInternalServiceGetUserProfileProcedure is the fully-qualified name of the
	// IdentityInternalService's GetUserProfile RPC.
	IdentityInternalServiceGetUserProfileProcedure = "/watch_together.internal.v1.IdentityInternalService/GetUserProfile"
)

// IdentityInternalServiceClient is a client for the
// watch_together.internal.v1.IdentityInternalService service.
type IdentityInternalServiceClient interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	VerifyAccessToken(context.Context, *connect.Request[v1.VerifyAccessTokenRequest]) (*connect.Response[v1.VerifyAccessTokenResponse], error)
	GetUserProfile(context.Context, *connect.Request[v1.GetUserProfileRequest]) (*connect.Response[v1.GetUserProfileResponse], error)
}

// NewIdentityInternalServiceClient constructs a client for the
// watch_together.internal.v1.IdentityInternalService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityInternalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityInternalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityInternalServiceMethods := v1.File_server_api_internal_v1_identity_proto.Services().ByName("IdentityInternalService").Methods()
	return &identityInternalServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+IdentityInternalServiceRegisterProcedure,
			connect.WithSchema(identityInternalServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+IdentityInternalServiceLoginProcedure,
			connect.WithSchema(identityInternalServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		verifyAccessToken: connect.NewClient[v1.VerifyAccessTokenRequest, v1.VerifyAccessTokenResponse](
			httpClient,
			baseURL+IdentityInternalServiceVerifyAccessTokenProcedure,
			connect.WithSchema(identityInternalServiceMethods.ByName("VerifyAccessToken")),
			connect.WithClientOptions(opts...),
		),
		getUserProfile: connect.NewClient[v1.GetUserProfileRequest, v1.GetUserProfileResponse](
			httpClient,
			baseURL+IdentityInternalServiceGetUserProfileProcedure,
			connect.WithSchema(identityInternalServiceMethods.ByName("GetUserProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityInternalServiceClient implements IdentityInternalServiceClient.
type identityInternalServiceClient struct {
	register          *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	login             *connect.Client[v1.LoginRequest, v1.LoginResponse]
	verifyAccessToken *connect.Client[v1.VerifyAccessTokenRequest, v1.VerifyAccessTokenResponse]
	getUserProfile    *connect.Client[v1.GetUserProfileRequest, v1.GetUserProfileResponse]
}

// Register calls watch_together.internal.v1.IdentityInternalService.Register.
func (c *identityInternalServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls watch_together.internal.v1.IdentityInternalService.Login.
func (c *identityInternalServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// VerifyAccessToken calls watch_together.internal.v1.IdentityInternalService.VerifyAccessToken.
func (c *identityInternalServiceClient) VerifyAccessToken(ctx context.Context, req *connect.Request[v1.VerifyAccessTokenRequest]) (*connect.Response[v1.VerifyAccessTokenResponse], error) {
	return c.verifyAccessToken.CallUnary(ctx, req)
}

// GetUserProfile calls watch_together.internal.v1.IdentityInternalService.GetUserProfile.
func (c *identityInternalServiceClient) GetUserProfile(ctx context.Context, req *connect.Request[v1.GetUserProfileRequest]) (*connect.Response[v1.GetUserProfileResponse], error) {
	return c.getUserProfile.CallUnary(ctx, req)
}

// IdentityInternalServiceHandler is an implementation of the
// watch_together.internal.v1.IdentityInternalService service.
type IdentityInternalServiceHandler interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	VerifyAccessToken(context.Context, *connect.Request[v1.VerifyAccessTokenRequest]) (*connect.Response[v1.VerifyAccessTokenResponse], error)
	GetUserProfile(context.Context, *connect.Request[v1.GetUserProfileRequest]) (*connect.Response[v1.GetUserProfileResponse], error)
}

// NewIdentityInternalServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityInternalServiceHandler(svc IdentityInternalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityInternalServiceMethods := v1.File_server_api_internal_v1_identity_proto.Services().ByName("IdentityInternalService").Methods()
	identityInternalServiceRegisterHandler := connect.NewUnaryHandler(
		IdentityInternalServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(identityInternalServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	identityInternalServiceLoginHandler := connect.NewUnaryHandler(
		IdentityInternalServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(identityInternalServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	identityInternalServiceVerifyAccessTokenHandler := connect.NewUnaryHandler(
		IdentityInternalServiceVerifyAccessTokenProcedure,
		svc.VerifyAccessToken,
		connect.WithSchema(identityInternalServiceMethods.ByName("VerifyAccessToken")),
		connect.WithHandlerOptions(opts...),
	)
	identityInternalServiceGetUserProfileHandler := connect.NewUnaryHandler(
		IdentityInternalServiceGetUserProfileProcedure,
		svc.GetUserProfile,
		connect.WithSchema(identityInternalServiceMethods.ByName("GetUserProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/watch_together.internal.v1.IdentityInternalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityInternalServiceRegisterProcedure:
			identityInternalServiceRegisterHandler.ServeHTTP(w, r)
		case IdentityInternalServiceLoginProcedure:
			identityInternalServiceLoginHandler.ServeHTTP(w, r)
		case IdentityInternalServiceVerifyAccessTokenProcedure:
			identityInternalServiceVerifyAccessTokenHandler.ServeHTTP(w, r)
		case IdentityInternalServiceGetUserProfileProcedure:
			identityInternalServiceGetUserProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityInternalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityInternalServiceHandler struct{}

func (UnimplementedIdentityInternalServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.IdentityInternalService.Register is not implemented"))
}

func (UnimplementedIdentityInternalServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.IdentityInternalService.Login is not implemented"))
}

func (UnimplementedIdentityInternalServiceHandler) VerifyAccessToken(context.Context, *connect.Request[v1.VerifyAccessTokenRequest]) (*connect.Response[v1.VerifyAccessTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.IdentityInternalService.VerifyAccessToken is not implemented"))
}

func (UnimplementedIdentityInternalServiceHandler) GetUserProfile(context.Context, *connect.Request[v1.GetUserProfileRequest]) (*connect.Response[v1.GetUserProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.IdentityInternalService.GetUserProfile is not implemented"))
}
