// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server/api/internal/v1/media.proto

package internalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "watch_together/server/internal/rpcgen/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MediaInternalServiceName is the fully-qualified name of the MediaInternalService service.
	MediaInternalServiceName = "watch_together.internal.v1.MediaInternalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MediaInternalServiceListTagsProcedure is the fully-qualified name of the MediaInternalService's
	// ListTags RPC.
	MediaInternalServiceListTagsProcedure = "/watch_together.internal.v1.MediaInternalService/ListTags"
	// MediaInternalServiceSearchItemsProcedure is the fully-qualified name of the
	// MediaInternalService's SearchItems RPC.
	MediaInternalServiceSearchItemsProcedure = "/watch_together.internal.v1.MediaInternalService/SearchItems"
	// MediaInternalServiceGetPlaybackItemProcedure is the fully-qualified name of the
	// MediaInternalService's GetPlaybackItem RPC.
	MediaInternalServiceGetPlaybackItemProcedure = "/watch_together.internal.v1.MediaInternalService/GetPlaybackItem"
	// MediaInternalServiceAuthorizePlaybackProcedure is the fully-qualified name of the
	// MediaInternalService's AuthorizePlayback RPC.
	MediaInternalServiceAuthorizePlaybackProcedure = "/watch_together.internal.v1.MediaInternalService/AuthorizePlayback"
	// MediaInternalServiceGetEpisodeDetailProcedure is the fully-qualified name of the
	// MediaInternalService's GetEpisodeDetail RPC.
	MediaInternalServiceGetEpisodeDetailProcedure = "/watch_together.internal.v1.MediaInternalService/GetEpisodeDetail"
	// MediaInternalServiceValidatePlayableEpisodeProcedure is the fully-qualified name of the
	// MediaInternalService's ValidatePlayableEpisode RPC.
	MediaInternalServiceValidatePlayableEpisodeProcedure = "/watch_together.internal.v1.MediaInternalService/ValidatePlayableEpisode"
)

// MediaInternalServiceClient is a client for the watch_together.internal.v1.MediaInternalService
// service.
type MediaInternalServiceClient interface {
	ListTags(context.Context, *connect.Request[v1.ListTagsRequest]) (*connect.Response[v1.ListTagsResponse], error)
	SearchItems(context.Context, *connect.Request[v1.SearchItemsRequest]) (*connect.Response[v1.SearchItemsResponse], error)
	GetPlaybackItem(context.Context, *connect.Request[v1.GetPlaybackItemRequest]) (*connect.Response[v1.GetPlaybackItemResponse], error)
	AuthorizePlayback(context.Context, *connect.Request[v1.AuthorizePlaybackRequest]) (*connect.Response[v1.AuthorizePlaybackResponse], error)
	GetEpisodeDetail(context.Context, *connect.Request[v1.GetEpisodeDetailRequest]) (*connect.Response[v1.GetEpisodeDetailResponse], error)
	ValidatePlayableEpisode(context.Context, *connect.Request[v1.ValidatePlayableEpisodeRequest]) (*connect.Response[v1.ValidatePlayableEpisodeResponse], error)
}

// NewMediaInternalServiceClient constructs a client for the
// watch_together.internal.v1.MediaInternalService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMediaInternalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MediaInternalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mediaInternalServiceMethods := v1.File_server_api_internal_v1_media_proto.Services().ByName("MediaInternalService").Methods()
	return &mediaInternalServiceClient{
		listTags: connect.NewClient[v1.ListTagsRequest, v1.ListTagsResponse](
			httpClient,
			baseURL+MediaInternalServiceListTagsProcedure,
			connect.WithSchema(mediaInternalServiceMethods.ByName("ListTags")),
			connect.WithClientOptions(opts...),
		),
		searchItems: connect.NewClient[v1.SearchItemsRequest, v1.SearchItemsResponse](
			httpClient,
			baseURL+MediaInternalServiceSearchItemsProcedure,
			connect.WithSchema(mediaInternalServiceMethods.ByName("SearchItems")),
			connect.WithClientOptions(opts...),
		),
		getPlaybackItem: connect.NewClient[v1.GetPlaybackItemRequest, v1.GetPlaybackItemResponse](
			httpClient,
			baseURL+MediaInternalServiceGetPlaybackItemProcedure,
			connect.WithSchema(mediaInternalServiceMethods.ByName("GetPlaybackItem")),
			connect.WithClientOptions(opts...),
		),
		authorizePlayback: connect.NewClient[v1.AuthorizePlaybackRequest, v1.AuthorizePlaybackResponse](
			httpClient,
			baseURL+MediaInternalServiceAuthorizePlaybackProcedure,
			connect.WithSchema(mediaInternalServiceMethods.ByName("AuthorizePlayback")),
			connect.WithClientOptions(opts...),
		),
		getEpisodeDetail: connect.NewClient[v1.GetEpisodeDetailRequest, v1.GetEpisodeDetailResponse](
			httpClient,
			baseURL+MediaInternalServiceGetEpisodeDetailProcedure,
			connect.WithSchema(mediaInternalServiceMethods.ByName("GetEpisodeDetail")),
			connect.WithClientOptions(opts...),
		),
		validatePlayableEpisode: connect.NewClient[v1.ValidatePlayableEpisodeRequest, v1.ValidatePlayableEpisodeResponse](
			httpClient,
			baseURL+MediaInternalServiceValidatePlayableEpisodeProcedure,
			connect.WithSchema(mediaInternalServiceMethods.ByName("ValidatePlayableEpisode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mediaInternalServiceClient implements MediaInternalServiceClient.
type mediaInternalServiceClient struct {
	listTags                *connect.Client[v1.ListTagsRequest, v1.ListTagsResponse]
	searchItems             *connect.Client[v1.SearchItemsRequest, v1.SearchItemsResponse]
	getPlaybackItem         *connect.Client[v1.GetPlaybackItemRequest, v1.GetPlaybackItemResponse]
	authorizePlayback       *connect.Client[v1.AuthorizePlaybackRequest, v1.AuthorizePlaybackResponse]
	getEpisodeDetail        *connect.Client[v1.GetEpisodeDetailRequest, v1.GetEpisodeDetailResponse]
	validatePlayableEpisode *connect.Client[v1.ValidatePlayableEpisodeRequest, v1.ValidatePlayableEpisodeResponse]
}

// ListTags calls watch_together.internal.v1.MediaInternalService.ListTags.
func (c *mediaInternalServiceClient) ListTags(ctx context.Context, req *connect.Request[v1.ListTagsRequest]) (*connect.Response[v1.ListTagsResponse], error) {
	return c.listTags.CallUnary(ctx, req)
}

// SearchItems calls watch_together.internal.v1.MediaInternalService.SearchItems.
func (c *mediaInternalServiceClient) SearchItems(ctx context.Context, req *connect.Request[v1.SearchItemsRequest]) (*connect.Response[v1.SearchItemsResponse], error) {
	return c.searchItems.CallUnary(ctx, req)
}

// GetPlaybackItem calls watch_together.internal.v1.MediaInternalService.GetPlaybackItem.
func (c *mediaInternalServiceClient) GetPlaybackItem(ctx context.Context, req *connect.Request[v1.GetPlaybackItemRequest]) (*connect.Response[v1.GetPlaybackItemResponse], error) {
	return c.getPlaybackItem.CallUnary(ctx, req)
}

// AuthorizePlayback calls watch_together.internal.v1.MediaInternalService.AuthorizePlayback.
func (c *mediaInternalServiceClient) AuthorizePlayback(ctx context.Context, req *connect.Request[v1.AuthorizePlaybackRequest]) (*connect.Response[v1.AuthorizePlaybackResponse], error) {
	return c.authorizePlayback.CallUnary(ctx, req)
}

// GetEpisodeDetail calls watch_together.internal.v1.MediaInternalService.GetEpisodeDetail.
func (c *mediaInternalServiceClient) GetEpisodeDetail(ctx context.Context, req *connect.Request[v1.GetEpisodeDetailRequest]) (*connect.Response[v1.GetEpisodeDetailResponse], error) {
	return c.getEpisodeDetail.CallUnary(ctx, req)
}

// ValidatePlayableEpisode calls
// watch_together.internal.v1.MediaInternalService.ValidatePlayableEpisode.
func (c *mediaInternalServiceClient) ValidatePlayableEpisode(ctx context.Context, req *connect.Request[v1.ValidatePlayableEpisodeRequest]) (*connect.Response[v1.ValidatePlayableEpisodeResponse], error) {
	return c.validatePlayableEpisode.CallUnary(ctx, req)
}

// MediaInternalServiceHandler is an implementation of the
// watch_together.internal.v1.MediaInternalService service.
type MediaInternalServiceHandler interface {
	ListTags(context.Context, *connect.Request[v1.ListTagsRequest]) (*connect.Response[v1.ListTagsResponse], error)
	SearchItems(context.Context, *connect.Request[v1.SearchItemsRequest]) (*connect.Response[v1.SearchItemsResponse], error)
	GetPlaybackItem(context.Context, *connect.Request[v1.GetPlaybackItemRequest]) (*connect.Response[v1.GetPlaybackItemResponse], error)
	AuthorizePlayback(context.Context, *connect.Request[v1.AuthorizePlaybackRequest]) (*connect.Response[v1.AuthorizePlaybackResponse], error)
	GetEpisodeDetail(context.Context, *connect.Request[v1.GetEpisodeDetailRequest]) (*connect.Response[v1.GetEpisodeDetailResponse], error)
	ValidatePlayableEpisode(context.Context, *connect.Request[v1.ValidatePlayableEpisodeRequest]) (*connect.Response[v1.ValidatePlayableEpisodeResponse], error)
}

// NewMediaInternalServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMediaInternalServiceHandler(svc MediaInternalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mediaInternalServiceMethods := v1.File_server_api_internal_v1_media_proto.Services().ByName("MediaInternalService").Methods()
	mediaInternalServiceListTagsHandler := connect.NewUnaryHandler(
		MediaInternalServiceListTagsProcedure,
		svc.ListTags,
		connect.WithSchema(mediaInternalServiceMethods.ByName("ListTags")),
		connect.WithHandlerOptions(opts...),
	)
	mediaInternalServiceSearchItemsHandler := connect.NewUnaryHandler(
		MediaInternalServiceSearchItemsProcedure,
		svc.SearchItems,
		connect.WithSchema(mediaInternalServiceMethods.ByName("SearchItems")),
		connect.WithHandlerOptions(opts...),
	)
	mediaInternalServiceGetPlaybackItemHandler := connect.NewUnaryHandler(
		MediaInternalServiceGetPlaybackItemProcedure,
		svc.GetPlaybackItem,
		connect.WithSchema(mediaInternalServiceMethods.ByName("GetPlaybackItem")),
		connect.WithHandlerOptions(opts...),
	)
	mediaInternalServiceAuthorizePlaybackHandler := connect.NewUnaryHandler(
		MediaInternalServiceAuthorizePlaybackProcedure,
		svc.AuthorizePlayback,
		connect.WithSchema(mediaInternalServiceMethods.ByName("AuthorizePlayback")),
		connect.WithHandlerOptions(opts...),
	)
	mediaInternalServiceGetEpisodeDetailHandler := connect.NewUnaryHandler(
		MediaInternalServiceGetEpisodeDetailProcedure,
		svc.GetEpisodeDetail,
		connect.WithSchema(mediaInternalServiceMethods.ByName("GetEpisodeDetail")),
		connect.WithHandlerOptions(opts...),
	)
	mediaInternalServiceValidatePlayableEpisodeHandler := connect.NewUnaryHandler(
		MediaInternalServiceValidatePlayableEpisodeProcedure,
		svc.ValidatePlayableEpisode,
		connect.WithSchema(mediaInternalServiceMethods.ByName("ValidatePlayableEpisode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/watch_together.internal.v1.MediaInternalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MediaInternalServiceListTagsProcedure:
			mediaInternalServiceListTagsHandler.ServeHTTP(w, r)
		case MediaInternalServiceSearchItemsProcedure:
			mediaInternalServiceSearchItemsHandler.ServeHTTP(w, r)
		case MediaInternalServiceGetPlaybackItemProcedure:
			mediaInternalServiceGetPlaybackItemHandler.ServeHTTP(w, r)
		case MediaInternalServiceAuthorizePlaybackProcedure:
			mediaInternalServiceAuthorizePlaybackHandler.ServeHTTP(w, r)
		case MediaInternalServiceGetEpisodeDetailProcedure:
			mediaInternalServiceGetEpisodeDetailHandler.ServeHTTP(w, r)
		case MediaInternalServiceValidatePlayableEpisodeProcedure:
			mediaInternalServiceValidatePlayableEpisodeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMediaInternalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMediaInternalServiceHandler struct{}

func (UnimplementedMediaInternalServiceHandler) ListTags(context.Context, *connect.Request[v1.ListTagsRequest]) (*connect.Response[v1.ListTagsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.MediaInternalService.ListTags is not implemented"))
}

func (UnimplementedMediaInternalServiceHandler) SearchItems(context.Context, *connect.Request[v1.SearchItemsRequest]) (*connect.Response[v1.SearchItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.MediaInternalService.SearchItems is not implemented"))
}

func (UnimplementedMediaInternalServiceHandler) GetPlaybackItem(context.Context, *connect.Request[v1.GetPlaybackItemRequest]) (*connect.Response[v1.GetPlaybackItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.MediaInternalService.GetPlaybackItem is not implemented"))
}

func (UnimplementedMediaInternalServiceHandler) AuthorizePlayback(context.Context, *connect.Request[v1.AuthorizePlaybackRequest]) (*connect.Response[v1.AuthorizePlaybackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.MediaInternalService.AuthorizePlayback is not implemented"))
}

func (UnimplementedMediaInternalServiceHandler) GetEpisodeDetail(context.Context, *connect.Request[v1.GetEpisodeDetailRequest]) (*connect.Response[v1.GetEpisodeDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.MediaInternalService.GetEpisodeDetail is not implemented"))
}

func (UnimplementedMediaInternalServiceHandler) ValidatePlayableEpisode(context.Context, *connect.Request[v1.ValidatePlayableEpisodeRequest]) (*connect.Response[v1.ValidatePlayableEpisodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.MediaInternalService.ValidatePlayableEpisode is not implemented"))
}
