// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server/api/internal/v1/progress.proto

package internalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "watch_together/server/internal/rpcgen/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProgressInternalServiceName is the fully-qualified name of the ProgressInternalService service.
	ProgressInternalServiceName = "watch_together.internal.v1.ProgressInternalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProgressInternalServiceUpdateProgressProcedure is the fully-qualified name of the
	// ProgressInternalService's UpdateProgress RPC.
	ProgressInternalServiceUpdateProgressProcedure = "/watch_together.internal.v1.ProgressInternalService/UpdateProgress"
	// ProgressInternalServiceGetUserProgressProcedure is the fully-qualified name of the
	// ProgressInternalService's GetUserProgress RPC.
	ProgressInternalServiceGetUserProgressProcedure = "/watch_together.internal.v1.ProgressInternalService/GetUserProgress"
	// ProgressInternalServiceBatchGetUserProgressProcedure is the fully-qualified name of the
	// ProgressInternalService's BatchGetUserProgress RPC.
	ProgressInternalServiceBatchGetUserProgressProcedure = "/watch_together.internal.v1.ProgressInternalService/BatchGetUserProgress"
	// ProgressInternalServiceListRecentUserProgressProcedure is the fully-qualified name of the
	// ProgressInternalService's ListRecentUserProgress RPC.
	ProgressInternalServiceListRecentUserProgressProcedure = "/watch_together.internal.v1.ProgressInternalService/ListRecentUserProgress"
)

// ProgressInternalServiceClient is a client for the
// watch_together.internal.v1.ProgressInternalService service.
type ProgressInternalServiceClient interface {
	UpdateProgress(context.Context, *connect.Request[v1.UpdateProgressRequest]) (*connect.Response[v1.UpdateProgressResponse], error)
	GetUserProgress(context.Context, *connect.Request[v1.GetUserProgressRequest]) (*connect.Response[v1.GetUserProgressResponse], error)
	BatchGetUserProgress(context.Context, *connect.Request[v1.BatchGetUserProgressRequest]) (*connect.Response[v1.BatchGetUserProgressResponse], error)
	ListRecentUserProgress(context.Context, *connect.Request[v1.ListRecentUserProgressRequest]) (*connect.Response[v1.ListRecentUserProgressResponse], error)
}

// NewProgressInternalServiceClient constructs a client for the
// watch_together.internal.v1.ProgressInternalService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProgressInternalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProgressInternalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	progressInternalServiceMethods := v1.File_server_api_internal_v1_progress_proto.Services().ByName("ProgressInternalService").Methods()
	return &progressInternalServiceClient{
		updateProgress: connect.NewClient[v1.UpdateProgressRequest, v1.UpdateProgressResponse](
			httpClient,
			baseURL+ProgressInternalServiceUpdateProgressProcedure,
			connect.WithSchema(progressInternalServiceMethods.ByName("UpdateProgress")),
			connect.WithClientOptions(opts...),
		),
		getUserProgress: connect.NewClient[v1.GetUserProgressRequest, v1.GetUserProgressResponse](
			httpClient,
			baseURL+ProgressInternalServiceGetUserProgressProcedure,
			connect.WithSchema(progressInternalServiceMethods.ByName("GetUserProgress")),
			connect.WithClientOptions(opts...),
		),
		batchGetUserProgress: connect.NewClient[v1.BatchGetUserProgressRequest, v1.BatchGetUserProgressResponse](
			httpClient,
			baseURL+ProgressInternalServiceBatchGetUserProgressProcedure,
			connect.WithSchema(progressInternalServiceMethods.ByName("BatchGetUserProgress")),
			connect.WithClientOptions(opts...),
		),
		listRecentUserProgress: connect.NewClient[v1.ListRecentUserProgressRequest, v1.ListRecentUserProgressResponse](
			httpClient,
			baseURL+ProgressInternalServiceListRecentUserProgressProcedure,
			connect.WithSchema(progressInternalServiceMethods.ByName("ListRecentUserProgress")),
			connect.WithClientOptions(opts...),
		),
	}
}

// progressInternalServiceClient implements ProgressInternalServiceClient.
type progressInternalServiceClient struct {
	updateProgress         *connect.Client[v1.UpdateProgressRequest, v1.UpdateProgressResponse]
	getUserProgress        *connect.Client[v1.GetUserProgressRequest, v1.GetUserProgressResponse]
	batchGetUserProgress   *connect.Client[v1.BatchGetUserProgressRequest, v1.BatchGetUserProgressResponse]
	listRecentUserProgress *connect.Client[v1.ListRecentUserProgressRequest, v1.ListRecentUserProgressResponse]
}

// UpdateProgress calls watch_together.internal.v1.ProgressInternalService.UpdateProgress.
func (c *progressInternalServiceClient) UpdateProgress(ctx context.Context, req *connect.Request[v1.UpdateProgressRequest]) (*connect.Response[v1.UpdateProgressResponse], error) {
	return c.updateProgress.CallUnary(ctx, req)
}

// GetUserProgress calls watch_together.internal.v1.ProgressInternalService.GetUserProgress.
func (c *progressInternalServiceClient) GetUserProgress(ctx context.Context, req *connect.Request[v1.GetUserProgressRequest]) (*connect.Response[v1.GetUserProgressResponse], error) {
	return c.getUserProgress.CallUnary(ctx, req)
}

// BatchGetUserProgress calls
// watch_together.internal.v1.ProgressInternalService.BatchGetUserProgress.
func (c *progressInternalServiceClient) BatchGetUserProgress(ctx context.Context, req *connect.Request[v1.BatchGetUserProgressRequest]) (*connect.Response[v1.BatchGetUserProgressResponse], error) {
	return c.batchGetUserProgress.CallUnary(ctx, req)
}

// ListRecentUserProgress calls
// watch_together.internal.v1.ProgressInternalService.ListRecentUserProgress.
func (c *progressInternalServiceClient) ListRecentUserProgress(ctx context.Context, req *connect.Request[v1.ListRecentUserProgressRequest]) (*connect.Response[v1.ListRecentUserProgressResponse], error) {
	return c.listRecentUserProgress.CallUnary(ctx, req)
}

// ProgressInternalServiceHandler is an implementation of the
// watch_together.internal.v1.ProgressInternalService service.
type ProgressInternalServiceHandler interface {
	UpdateProgress(context.Context, *connect.Request[v1.UpdateProgressRequest]) (*connect.Response[v1.UpdateProgressResponse], error)
	GetUserProgress(context.Context, *connect.Request[v1.GetUserProgressRequest]) (*connect.Response[v1.GetUserProgressResponse], error)
	BatchGetUserProgress(context.Context, *connect.Request[v1.BatchGetUserProgressRequest]) (*connect.Response[v1.BatchGetUserProgressResponse], error)
	ListRecentUserProgress(context.Context, *connect.Request[v1.ListRecentUserProgressRequest]) (*connect.Response[v1.ListRecentUserProgressResponse], error)
}

// NewProgressInternalServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProgressInternalServiceHandler(svc ProgressInternalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	progressInternalServiceMethods := v1.File_server_api_internal_v1_progress_proto.Services().ByName("ProgressInternalService").Methods()
	progressInternalServiceUpdateProgressHandler := connect.NewUnaryHandler(
		ProgressInternalServiceUpdateProgressProcedure,
		svc.UpdateProgress,
		connect.WithSchema(progressInternalServiceMethods.ByName("UpdateProgress")),
		connect.WithHandlerOptions(opts...),
	)
	progressInternalServiceGetUserProgressHandler := connect.NewUnaryHandler(
		ProgressInternalServiceGetUserProgressProcedure,
		svc.GetUserProgress,
		connect.WithSchema(progressInternalServiceMethods.ByName("GetUserProgress")),
		connect.WithHandlerOptions(opts...),
	)
	progressInternalServiceBatchGetUserProgressHandler := connect.NewUnaryHandler(
		ProgressInternalServiceBatchGetUserProgressProcedure,
		svc.BatchGetUserProgress,
		connect.WithSchema(progressInternalServiceMethods.ByName("BatchGetUserProgress")),
		connect.WithHandlerOptions(opts...),
	)
	progressInternalServiceListRecentUserProgressHandler := connect.NewUnaryHandler(
		ProgressInternalServiceListRecentUserProgressProcedure,
		svc.ListRecentUserProgress,
		connect.WithSchema(progressInternalServiceMethods.ByName("ListRecentUserProgress")),
		connect.WithHandlerOptions(opts...),
	)
	return "/watch_together.internal.v1.ProgressInternalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProgressInternalServiceUpdateProgressProcedure:
			progressInternalServiceUpdateProgressHandler.ServeHTTP(w, r)
		case ProgressInternalServiceGetUserProgressProcedure:
			progressInternalServiceGetUserProgressHandler.ServeHTTP(w, r)
		case ProgressInternalServiceBatchGetUserProgressProcedure:
			progressInternalServiceBatchGetUserProgressHandler.ServeHTTP(w, r)
		case ProgressInternalServiceListRecentUserProgressProcedure:
			progressInternalServiceListRecentUserProgressHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProgressInternalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProgressInternalServiceHandler struct{}

func (UnimplementedProgressInternalServiceHandler) UpdateProgress(context.Context, *connect.Request[v1.UpdateProgressRequest]) (*connect.Response[v1.UpdateProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.ProgressInternalService.UpdateProgress is not implemented"))
}

func (UnimplementedProgressInternalServiceHandler) GetUserProgress(context.Context, *connect.Request[v1.GetUserProgressRequest]) (*connect.Response[v1.GetUserProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.ProgressInternalService.GetUserProgress is not implemented"))
}

func (UnimplementedProgressInternalServiceHandler) BatchGetUserProgress(context.Context, *connect.Request[v1.BatchGetUserProgressRequest]) (*connect.Response[v1.BatchGetUserProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.ProgressInternalService.BatchGetUserProgress is not implemented"))
}

func (UnimplementedProgressInternalServiceHandler) ListRecentUserProgress(context.Context, *connect.Request[v1.ListRecentUserProgressRequest]) (*connect.Response[v1.ListRecentUserProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.ProgressInternalService.ListRecentUserProgress is not implemented"))
}
