// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server/api/internal/v1/room.proto

package internalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "watch_together/server/internal/rpcgen/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoomInternalServiceName is the fully-qualified name of the RoomInternalService service.
	RoomInternalServiceName = "watch_together.internal.v1.RoomInternalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoomInternalServiceCreateRoomProcedure is the fully-qualified name of the RoomInternalService's
	// CreateRoom RPC.
	RoomInternalServiceCreateRoomProcedure = "/watch_together.internal.v1.RoomInternalService/CreateRoom"
	// RoomInternalServiceJoinRoomProcedure is the fully-qualified name of the RoomInternalService's
	// JoinRoom RPC.
	RoomInternalServiceJoinRoomProcedure = "/watch_together.internal.v1.RoomInternalService/JoinRoom"
	// RoomInternalServiceLeaveRoomProcedure is the fully-qualified name of the RoomInternalService's
	// LeaveRoom RPC.
	RoomInternalServiceLeaveRoomProcedure = "/watch_together.internal.v1.RoomInternalService/LeaveRoom"
	// RoomInternalServiceGetRoomDetailProcedure is the fully-qualified name of the
	// RoomInternalService's GetRoomDetail RPC.
	RoomInternalServiceGetRoomDetailProcedure = "/watch_together.internal.v1.RoomInternalService/GetRoomDetail"
	// RoomInternalServiceIsActiveMemberProcedure is the fully-qualified name of the
	// RoomInternalService's IsActiveMember RPC.
	RoomInternalServiceIsActiveMemberProcedure = "/watch_together.internal.v1.RoomInternalService/IsActiveMember"
)

// RoomInternalServiceClient is a client for the watch_together.internal.v1.RoomInternalService
// service.
type RoomInternalServiceClient interface {
	CreateRoom(context.Context, *connect.Request[v1.CreateRoomRequest]) (*connect.Response[v1.CreateRoomResponse], error)
	JoinRoom(context.Context, *connect.Request[v1.JoinRoomRequest]) (*connect.Response[v1.JoinRoomResponse], error)
	LeaveRoom(context.Context, *connect.Request[v1.LeaveRoomRequest]) (*connect.Response[v1.LeaveRoomResponse], error)
	GetRoomDetail(context.Context, *connect.Request[v1.GetRoomDetailRequest]) (*connect.Response[v1.GetRoomDetailResponse], error)
	IsActiveMember(context.Context, *connect.Request[v1.IsActiveMemberRequest]) (*connect.Response[v1.IsActiveMemberResponse], error)
}

// NewRoomInternalServiceClient constructs a client for the
// watch_together.internal.v1.RoomInternalService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoomInternalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoomInternalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roomInternalServiceMethods := v1.File_server_api_internal_v1_room_proto.Services().ByName("RoomInternalService").Methods()
	return &roomInternalServiceClient{
		createRoom: connect.NewClient[v1.CreateRoomRequest, v1.CreateRoomResponse](
			httpClient,
			baseURL+RoomInternalServiceCreateRoomProcedure,
			connect.WithSchema(roomInternalServiceMethods.ByName("CreateRoom")),
			connect.WithClientOptions(opts...),
		),
		joinRoom: connect.NewClient[v1.JoinRoomRequest, v1.JoinRoomResponse](
			httpClient,
			baseURL+RoomInternalServiceJoinRoomProcedure,
			connect.WithSchema(roomInternalServiceMethods.ByName("JoinRoom")),
			connect.WithClientOptions(opts...),
		),
		leaveRoom: connect.NewClient[v1.LeaveRoomRequest, v1.LeaveRoomResponse](
			httpClient,
			baseURL+RoomInternalServiceLeaveRoomProcedure,
			connect.WithSchema(roomInternalServiceMethods.ByName("LeaveRoom")),
			connect.WithClientOptions(opts...),
		),
		getRoomDetail: connect.NewClient[v1.GetRoomDetailRequest, v1.GetRoomDetailResponse](
			httpClient,
			baseURL+RoomInternalServiceGetRoomDetailProcedure,
			connect.WithSchema(roomInternalServiceMethods.ByName("GetRoomDetail")),
			connect.WithClientOptions(opts...),
		),
		isActiveMember: connect.NewClient[v1.IsActiveMemberRequest, v1.IsActiveMemberResponse](
			httpClient,
			baseURL+RoomInternalServiceIsActiveMemberProcedure,
			connect.WithSchema(roomInternalServiceMethods.ByName("IsActiveMember")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roomInternalServiceClient implements RoomInternalServiceClient.
type roomInternalServiceClient struct {
	createRoom     *connect.Client[v1.CreateRoomRequest, v1.CreateRoomResponse]
	joinRoom       *connect.Client[v1.JoinRoomRequest, v1.JoinRoomResponse]
	leaveRoom      *connect.Client[v1.LeaveRoomRequest, v1.LeaveRoomResponse]
	getRoomDetail  *connect.Client[v1.GetRoomDetailRequest, v1.GetRoomDetailResponse]
	isActiveMember *connect.Client[v1.IsActiveMemberRequest, v1.IsActiveMemberResponse]
}

// CreateRoom calls watch_together.internal.v1.RoomInternalService.CreateRoom.
func (c *roomInternalServiceClient) CreateRoom(ctx context.Context, req *connect.Request[v1.CreateRoomRequest]) (*connect.Response[v1.CreateRoomResponse], error) {
	return c.createRoom.CallUnary(ctx, req)
}

// JoinRoom calls watch_together.internal.v1.RoomInternalService.JoinRoom.
func (c *roomInternalServiceClient) JoinRoom(ctx context.Context, req *connect.Request[v1.JoinRoomRequest]) (*connect.Response[v1.JoinRoomResponse], error) {
	return c.joinRoom.CallUnary(ctx, req)
}

// LeaveRoom calls watch_together.internal.v1.RoomInternalService.LeaveRoom.
func (c *roomInternalServiceClient) LeaveRoom(ctx context.Context, req *connect.Request[v1.LeaveRoomRequest]) (*connect.Response[v1.LeaveRoomResponse], error) {
	return c.leaveRoom.CallUnary(ctx, req)
}

// GetRoomDetail calls watch_together.internal.v1.RoomInternalService.GetRoomDetail.
func (c *roomInternalServiceClient) GetRoomDetail(ctx context.Context, req *connect.Request[v1.GetRoomDetailRequest]) (*connect.Response[v1.GetRoomDetailResponse], error) {
	return c.getRoomDetail.CallUnary(ctx, req)
}

// IsActiveMember calls watch_together.internal.v1.RoomInternalService.IsActiveMember.
func (c *roomInternalServiceClient) IsActiveMember(ctx context.Context, req *connect.Request[v1.IsActiveMemberRequest]) (*connect.Response[v1.IsActiveMemberResponse], error) {
	return c.isActiveMember.CallUnary(ctx, req)
}

// RoomInternalServiceHandler is an implementation of the
// watch_together.internal.v1.RoomInternalService service.
type RoomInternalServiceHandler interface {
	CreateRoom(context.Context, *connect.Request[v1.CreateRoomRequest]) (*connect.Response[v1.CreateRoomResponse], error)
	JoinRoom(context.Context, *connect.Request[v1.JoinRoomRequest]) (*connect.Response[v1.JoinRoomResponse], error)
	LeaveRoom(context.Context, *connect.Request[v1.LeaveRoomRequest]) (*connect.Response[v1.LeaveRoomResponse], error)
	GetRoomDetail(context.Context, *connect.Request[v1.GetRoomDetailRequest]) (*connect.Response[v1.GetRoomDetailResponse], error)
	IsActiveMember(context.Context, *connect.Request[v1.IsActiveMemberRequest]) (*connect.Response[v1.IsActiveMemberResponse], error)
}

// NewRoomInternalServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoomInternalServiceHandler(svc RoomInternalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roomInternalServiceMethods := v1.File_server_api_internal_v1_room_proto.Services().ByName("RoomInternalService").Methods()
	roomInternalServiceCreateRoomHandler := connect.NewUnaryHandler(
		RoomInternalServiceCreateRoomProcedure,
		svc.CreateRoom,
		connect.WithSchema(roomInternalServiceMethods.ByName("CreateRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomInternalServiceJoinRoomHandler := connect.NewUnaryHandler(
		RoomInternalServiceJoinRoomProcedure,
		svc.JoinRoom,
		connect.WithSchema(roomInternalServiceMethods.ByName("JoinRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomInternalServiceLeaveRoomHandler := connect.NewUnaryHandler(
		RoomInternalServiceLeaveRoomProcedure,
		svc.LeaveRoom,
		connect.WithSchema(roomInternalServiceMethods.ByName("LeaveRoom")),
		connect.WithHandlerOptions(opts...),
	)
	roomInternalServiceGetRoomDetailHandler := connect.NewUnaryHandler(
		RoomInternalServiceGetRoomDetailProcedure,
		svc.GetRoomDetail,
		connect.WithSchema(roomInternalServiceMethods.ByName("GetRoomDetail")),
		connect.WithHandlerOptions(opts...),
	)
	roomInternalServiceIsActiveMemberHandler := connect.NewUnaryHandler(
		RoomInternalServiceIsActiveMemberProcedure,
		svc.IsActiveMember,
		connect.WithSchema(roomInternalServiceMethods.ByName("IsActiveMember")),
		connect.WithHandlerOptions(opts...),
	)
	return "/watch_together.internal.v1.RoomInternalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoomInternalServiceCreateRoomProcedure:
			roomInternalServiceCreateRoomHandler.ServeHTTP(w, r)
		case RoomInternalServiceJoinRoomProcedure:
			roomInternalServiceJoinRoomHandler.ServeHTTP(w, r)
		case RoomInternalServiceLeaveRoomProcedure:
			roomInternalServiceLeaveRoomHandler.ServeHTTP(w, r)
		case RoomInternalServiceGetRoomDetailProcedure:
			roomInternalServiceGetRoomDetailHandler.ServeHTTP(w, r)
		case RoomInternalServiceIsActiveMemberProcedure:
			roomInternalServiceIsActiveMemberHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoomInternalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoomInternalServiceHandler struct{}

func (UnimplementedRoomInternalServiceHandler) CreateRoom(context.Context, *connect.Request[v1.CreateRoomRequest]) (*connect.Response[v1.CreateRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomInternalService.CreateRoom is not implemented"))
}

func (UnimplementedRoomInternalServiceHandler) JoinRoom(context.Context, *connect.Request[v1.JoinRoomRequest]) (*connect.Response[v1.JoinRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomInternalService.JoinRoom is not implemented"))
}

func (UnimplementedRoomInternalServiceHandler) LeaveRoom(context.Context, *connect.Request[v1.LeaveRoomRequest]) (*connect.Response[v1.LeaveRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomInternalService.LeaveRoom is not implemented"))
}

func (UnimplementedRoomInternalServiceHandler) GetRoomDetail(context.Context, *connect.Request[v1.GetRoomDetailRequest]) (*connect.Response[v1.GetRoomDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomInternalService.GetRoomDetail is not implemented"))
}

func (UnimplementedRoomInternalServiceHandler) IsActiveMember(context.Context, *connect.Request[v1.IsActiveMemberRequest]) (*connect.Response[v1.IsActiveMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.RoomInternalService.IsActiveMember is not implemented"))
}
