// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: server/api/internal/v1/timeline.proto

package internalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "watch_together/server/internal/rpcgen/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TimelineInternalServiceName is the fully-qualified name of the TimelineInternalService service.
	TimelineInternalServiceName = "watch_together.internal.v1.TimelineInternalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TimelineInternalServiceRecordTimelineEventProcedure is the fully-qualified name of the
	// TimelineInternalService's RecordTimelineEvent RPC.
	TimelineInternalServiceRecordTimelineEventProcedure = "/watch_together.internal.v1.TimelineInternalService/RecordTimelineEvent"
	// TimelineInternalServiceListRoomEventsProcedure is the fully-qualified name of the
	// TimelineInternalService's ListRoomEvents RPC.
	TimelineInternalServiceListRoomEventsProcedure = "/watch_together.internal.v1.TimelineInternalService/ListRoomEvents"
	// TimelineInternalServiceListUnpublishedRoomEventsProcedure is the fully-qualified name of the
	// TimelineInternalService's ListUnpublishedRoomEvents RPC.
	TimelineInternalServiceListUnpublishedRoomEventsProcedure = "/watch_together.internal.v1.TimelineInternalService/ListUnpublishedRoomEvents"
)

// TimelineInternalServiceClient is a client for the
// watch_together.internal.v1.TimelineInternalService service.
type TimelineInternalServiceClient interface {
	RecordTimelineEvent(context.Context, *connect.Request[v1.RecordTimelineEventRequest]) (*connect.Response[v1.RecordTimelineEventResponse], error)
	ListRoomEvents(context.Context, *connect.Request[v1.ListRoomEventsRequest]) (*connect.Response[v1.ListRoomEventsResponse], error)
	ListUnpublishedRoomEvents(context.Context, *connect.Request[v1.ListUnpublishedRoomEventsRequest]) (*connect.Response[v1.ListUnpublishedRoomEventsResponse], error)
}

// NewTimelineInternalServiceClient constructs a client for the
// watch_together.internal.v1.TimelineInternalService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTimelineInternalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TimelineInternalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	timelineInternalServiceMethods := v1.File_server_api_internal_v1_timeline_proto.Services().ByName("TimelineInternalService").Methods()
	return &timelineInternalServiceClient{
		recordTimelineEvent: connect.NewClient[v1.RecordTimelineEventRequest, v1.RecordTimelineEventResponse](
			httpClient,
			baseURL+TimelineInternalServiceRecordTimelineEventProcedure,
			connect.WithSchema(timelineInternalServiceMethods.ByName("RecordTimelineEvent")),
			connect.WithClientOptions(opts...),
		),
		listRoomEvents: connect.NewClient[v1.ListRoomEventsRequest, v1.ListRoomEventsResponse](
			httpClient,
			baseURL+TimelineInternalServiceListRoomEventsProcedure,
			connect.WithSchema(timelineInternalServiceMethods.ByName("ListRoomEvents")),
			connect.WithClientOptions(opts...),
		),
		listUnpublishedRoomEvents: connect.NewClient[v1.ListUnpublishedRoomEventsRequest, v1.ListUnpublishedRoomEventsResponse](
			httpClient,
			baseURL+TimelineInternalServiceListUnpublishedRoomEventsProcedure,
			connect.WithSchema(timelineInternalServiceMethods.ByName("ListUnpublishedRoomEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// timelineInternalServiceClient implements TimelineInternalServiceClient.
type timelineInternalServiceClient struct {
	recordTimelineEvent       *connect.Client[v1.RecordTimelineEventRequest, v1.RecordTimelineEventResponse]
	listRoomEvents            *connect.Client[v1.ListRoomEventsRequest, v1.ListRoomEventsResponse]
	listUnpublishedRoomEvents *connect.Client[v1.ListUnpublishedRoomEventsRequest, v1.ListUnpublishedRoomEventsResponse]
}

// RecordTimelineEvent calls watch_together.internal.v1.TimelineInternalService.RecordTimelineEvent.
func (c *timelineInternalServiceClient) RecordTimelineEvent(ctx context.Context, req *connect.Request[v1.RecordTimelineEventRequest]) (*connect.Response[v1.RecordTimelineEventResponse], error) {
	return c.recordTimelineEvent.CallUnary(ctx, req)
}

// ListRoomEvents calls watch_together.internal.v1.TimelineInternalService.ListRoomEvents.
func (c *timelineInternalServiceClient) ListRoomEvents(ctx context.Context, req *connect.Request[v1.ListRoomEventsRequest]) (*connect.Response[v1.ListRoomEventsResponse], error) {
	return c.listRoomEvents.CallUnary(ctx, req)
}

// ListUnpublishedRoomEvents calls
// watch_together.internal.v1.TimelineInternalService.ListUnpublishedRoomEvents.
func (c *timelineInternalServiceClient) ListUnpublishedRoomEvents(ctx context.Context, req *connect.Request[v1.ListUnpublishedRoomEventsRequest]) (*connect.Response[v1.ListUnpublishedRoomEventsResponse], error) {
	return c.listUnpublishedRoomEvents.CallUnary(ctx, req)
}

// TimelineInternalServiceHandler is an implementation of the
// watch_together.internal.v1.TimelineInternalService service.
type TimelineInternalServiceHandler interface {
	RecordTimelineEvent(context.Context, *connect.Request[v1.RecordTimelineEventRequest]) (*connect.Response[v1.RecordTimelineEventResponse], error)
	ListRoomEvents(context.Context, *connect.Request[v1.ListRoomEventsRequest]) (*connect.Response[v1.ListRoomEventsResponse], error)
	ListUnpublishedRoomEvents(context.Context, *connect.Request[v1.ListUnpublishedRoomEventsRequest]) (*connect.Response[v1.ListUnpublishedRoomEventsResponse], error)
}

// NewTimelineInternalServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTimelineInternalServiceHandler(svc TimelineInternalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	timelineInternalServiceMethods := v1.File_server_api_internal_v1_timeline_proto.Services().ByName("TimelineInternalService").Methods()
	timelineInternalServiceRecordTimelineEventHandler := connect.NewUnaryHandler(
		TimelineInternalServiceRecordTimelineEventProcedure,
		svc.RecordTimelineEvent,
		connect.WithSchema(timelineInternalServiceMethods.ByName("RecordTimelineEvent")),
		connect.WithHandlerOptions(opts...),
	)
	timelineInternalServiceListRoomEventsHandler := connect.NewUnaryHandler(
		TimelineInternalServiceListRoomEventsProcedure,
		svc.ListRoomEvents,
		connect.WithSchema(timelineInternalServiceMethods.ByName("ListRoomEvents")),
		connect.WithHandlerOptions(opts...),
	)
	timelineInternalServiceListUnpublishedRoomEventsHandler := connect.NewUnaryHandler(
		TimelineInternalServiceListUnpublishedRoomEventsProcedure,
		svc.ListUnpublishedRoomEvents,
		connect.WithSchema(timelineInternalServiceMethods.ByName("ListUnpublishedRoomEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/watch_together.internal.v1.TimelineInternalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TimelineInternalServiceRecordTimelineEventProcedure:
			timelineInternalServiceRecordTimelineEventHandler.ServeHTTP(w, r)
		case TimelineInternalServiceListRoomEventsProcedure:
			timelineInternalServiceListRoomEventsHandler.ServeHTTP(w, r)
		case TimelineInternalServiceListUnpublishedRoomEventsProcedure:
			timelineInternalServiceListUnpublishedRoomEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTimelineInternalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTimelineInternalServiceHandler struct{}

func (UnimplementedTimelineInternalServiceHandler) RecordTimelineEvent(context.Context, *connect.Request[v1.RecordTimelineEventRequest]) (*connect.Response[v1.RecordTimelineEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.TimelineInternalService.RecordTimelineEvent is not implemented"))
}

func (UnimplementedTimelineInternalServiceHandler) ListRoomEvents(context.Context, *connect.Request[v1.ListRoomEventsRequest]) (*connect.Response[v1.ListRoomEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.TimelineInternalService.ListRoomEvents is not implemented"))
}

func (UnimplementedTimelineInternalServiceHandler) ListUnpublishedRoomEvents(context.Context, *connect.Request[v1.ListUnpublishedRoomEventsRequest]) (*connect.Response[v1.ListUnpublishedRoomEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("watch_together.internal.v1.TimelineInternalService.ListUnpublishedRoomEvents is not implemented"))
}
