// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: server/api/internal/v1/authority.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorityLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LeaseUntilMs  int64                  `protobuf:"varint,4,opt,name=lease_until_ms,json=leaseUntilMs,proto3" json:"lease_until_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorityLease) Reset() {
	*x = AuthorityLease{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityLease) ProtoMessage() {}

func (x *AuthorityLease) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityLease.ProtoReflect.Descriptor instead.
func (*AuthorityLease) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorityLease) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AuthorityLease) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AuthorityLease) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorityLease) GetLeaseUntilMs() int64 {
	if x != nil {
		return x.LeaseUntilMs
	}
	return 0
}

type GetRoomAuthorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomAuthorityRequest) Reset() {
	*x = GetRoomAuthorityRequest{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomAuthorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomAuthorityRequest) ProtoMessage() {}

func (x *GetRoomAuthorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomAuthorityRequest.ProtoReflect.Descriptor instead.
func (*GetRoomAuthorityRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomAuthorityRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetRoomAuthorityRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomAuthorityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Lease         *AuthorityLease        `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomAuthorityResponse) Reset() {
	*x = GetRoomAuthorityResponse{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomAuthorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomAuthorityResponse) ProtoMessage() {}

func (x *GetRoomAuthorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomAuthorityResponse.ProtoReflect.Descriptor instead.
func (*GetRoomAuthorityResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomAuthorityResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetRoomAuthorityResponse) GetLease() *AuthorityLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type ClaimRoomAuthorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRoomAuthorityRequest) Reset() {
	*x = ClaimRoomAuthorityRequest{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRoomAuthorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRoomAuthorityRequest) ProtoMessage() {}

func (x *ClaimRoomAuthorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRoomAuthorityRequest.ProtoReflect.Descriptor instead.
func (*ClaimRoomAuthorityRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimRoomAuthorityRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClaimRoomAuthorityRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ClaimRoomAuthorityRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ClaimRoomAuthorityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claimed       bool                   `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"`
	Lease         *AuthorityLease        `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRoomAuthorityResponse) Reset() {
	*x = ClaimRoomAuthorityResponse{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRoomAuthorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRoomAuthorityResponse) ProtoMessage() {}

func (x *ClaimRoomAuthorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRoomAuthorityResponse.ProtoReflect.Descriptor instead.
func (*ClaimRoomAuthorityResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimRoomAuthorityResponse) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *ClaimRoomAuthorityResponse) GetLease() *AuthorityLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RenewRoomAuthorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRoomAuthorityRequest) Reset() {
	*x = RenewRoomAuthorityRequest{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRoomAuthorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRoomAuthorityRequest) ProtoMessage() {}

func (x *RenewRoomAuthorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRoomAuthorityRequest.ProtoReflect.Descriptor instead.
func (*RenewRoomAuthorityRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{5}
}

func (x *RenewRoomAuthorityRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RenewRoomAuthorityRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RenewRoomAuthorityRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RenewRoomAuthorityRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type RenewRoomAuthorityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Renewed       bool                   `protobuf:"varint,1,opt,name=renewed,proto3" json:"renewed,omitempty"`
	Lease         *AuthorityLease        `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRoomAuthorityResponse) Reset() {
	*x = RenewRoomAuthorityResponse{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRoomAuthorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRoomAuthorityResponse) ProtoMessage() {}

func (x *RenewRoomAuthorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRoomAuthorityResponse.ProtoReflect.Descriptor instead.
func (*RenewRoomAuthorityResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{6}
}

func (x *RenewRoomAuthorityResponse) GetRenewed() bool {
	if x != nil {
		return x.Renewed
	}
	return false
}

func (x *RenewRoomAuthorityResponse) GetLease() *AuthorityLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type BeginRoomRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRoomRecoveryRequest) Reset() {
	*x = BeginRoomRecoveryRequest{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRoomRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRoomRecoveryRequest) ProtoMessage() {}

func (x *BeginRoomRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRoomRecoveryRequest.ProtoReflect.Descriptor instead.
func (*BeginRoomRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{7}
}

func (x *BeginRoomRecoveryRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BeginRoomRecoveryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BeginRoomRecoveryRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type BeginRoomRecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Lease         *AuthorityLease        `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRoomRecoveryResponse) Reset() {
	*x = BeginRoomRecoveryResponse{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRoomRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRoomRecoveryResponse) ProtoMessage() {}

func (x *BeginRoomRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRoomRecoveryResponse.ProtoReflect.Descriptor instead.
func (*BeginRoomRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{8}
}

func (x *BeginRoomRecoveryResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *BeginRoomRecoveryResponse) GetLease() *AuthorityLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type CompleteRoomRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRoomRecoveryRequest) Reset() {
	*x = CompleteRoomRecoveryRequest{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRoomRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRoomRecoveryRequest) ProtoMessage() {}

func (x *CompleteRoomRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRoomRecoveryRequest.ProtoReflect.Descriptor instead.
func (*CompleteRoomRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteRoomRecoveryRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CompleteRoomRecoveryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CompleteRoomRecoveryRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CompleteRoomRecoveryRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type CompleteRoomRecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completed     bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Lease         *AuthorityLease        `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRoomRecoveryResponse) Reset() {
	*x = CompleteRoomRecoveryResponse{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRoomRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRoomRecoveryResponse) ProtoMessage() {}

func (x *CompleteRoomRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRoomRecoveryResponse.ProtoReflect.Descriptor instead.
func (*CompleteRoomRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteRoomRecoveryResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *CompleteRoomRecoveryResponse) GetLease() *AuthorityLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type ApplyRoomControlRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Metadata               *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SourceInstanceId       string                 `protobuf:"bytes,2,opt,name=source_instance_id,json=sourceInstanceId,proto3" json:"source_instance_id,omitempty"`
	RoomId                 string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId                 string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId               string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ConnectionId           string                 `protobuf:"bytes,6,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Type                   string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Payload                []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestId              string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Seq                    int64                  `protobuf:"varint,10,opt,name=seq,proto3" json:"seq,omitempty"`
	ExpectedAuthorityEpoch int64                  `protobuf:"varint,11,opt,name=expected_authority_epoch,json=expectedAuthorityEpoch,proto3" json:"expected_authority_epoch,omitempty"`
	RequestedAtMs          int64                  `protobuf:"varint,12,opt,name=requested_at_ms,json=requestedAtMs,proto3" json:"requested_at_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ApplyRoomControlRequest) Reset() {
	*x = ApplyRoomControlRequest{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRoomControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRoomControlRequest) ProtoMessage() {}

func (x *ApplyRoomControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRoomControlRequest.ProtoReflect.Descriptor instead.
func (*ApplyRoomControlRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{11}
}

func (x *ApplyRoomControlRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ApplyRoomControlRequest) GetSourceInstanceId() string {
	if x != nil {
		return x.SourceInstanceId
	}
	return ""
}

func (x *ApplyRoomControlRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ApplyRoomControlRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApplyRoomControlRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ApplyRoomControlRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ApplyRoomControlRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApplyRoomControlRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApplyRoomControlRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApplyRoomControlRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ApplyRoomControlRequest) GetExpectedAuthorityEpoch() int64 {
	if x != nil {
		return x.ExpectedAuthorityEpoch
	}
	return 0
}

func (x *ApplyRoomControlRequest) GetRequestedAtMs() int64 {
	if x != nil {
		return x.RequestedAtMs
	}
	return 0
}

type ApplyRoomControlResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Seq            int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	AuthorityEpoch int64                  `protobuf:"varint,5,opt,name=authority_epoch,json=authorityEpoch,proto3" json:"authority_epoch,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyRoomControlResponse) Reset() {
	*x = ApplyRoomControlResponse{}
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRoomControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRoomControlResponse) ProtoMessage() {}

func (x *ApplyRoomControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_authority_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRoomControlResponse.ProtoReflect.Descriptor instead.
func (*ApplyRoomControlResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_authority_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyRoomControlResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ApplyRoomControlResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApplyRoomControlResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApplyRoomControlResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ApplyRoomControlResponse) GetAuthorityEpoch() int64 {
	if x != nil {
		return x.AuthorityEpoch
	}
	return 0
}

func (x *ApplyRoomControlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_server_api_internal_v1_authority_proto protoreflect.FileDescriptor

const file_server_api_internal_v1_authority_proto_rawDesc = "" +
	"\n" +
	"&server/api/internal/v1/authority.proto\x12\x1awatch_together.internal.v1\x1a#server/api/internal/v1/common.proto\"\x85\x01\n" +
	"\x0eAuthorityLease\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12$\n" +
	"\x0elease_until_ms\x18\x04 \x01(\x03R\fleaseUntilMs\"{\n" +
	"\x17GetRoomAuthorityRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"r\n" +
	"\x18GetRoomAuthorityResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12@\n" +
	"\x05lease\x18\x02 \x01(\v2*.watch_together.internal.v1.AuthorityLeaseR\x05lease\"\x9e\x01\n" +
	"\x19ClaimRoomAuthorityRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"x\n" +
	"\x1aClaimRoomAuthorityResponse\x12\x18\n" +
	"\aclaimed\x18\x01 \x01(\bR\aclaimed\x12@\n" +
	"\x05lease\x18\x02 \x01(\v2*.watch_together.internal.v1.AuthorityLeaseR\x05lease\"\xb4\x01\n" +
	"\x19RenewRoomAuthorityRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x03R\x05epoch\"x\n" +
	"\x1aRenewRoomAuthorityResponse\x12\x18\n" +
	"\arenewed\x18\x01 \x01(\bR\arenewed\x12@\n" +
	"\x05lease\x18\x02 \x01(\v2*.watch_together.internal.v1.AuthorityLeaseR\x05lease\"\x9d\x01\n" +
	"\x18BeginRoomRecoveryRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"w\n" +
	"\x19BeginRoomRecoveryResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12@\n" +
	"\x05lease\x18\x02 \x01(\v2*.watch_together.internal.v1.AuthorityLeaseR\x05lease\"\xb6\x01\n" +
	"\x1bCompleteRoomRecoveryRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x03R\x05epoch\"~\n" +
	"\x1cCompleteRoomRecoveryResponse\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x12@\n" +
	"\x05lease\x18\x02 \x01(\v2*.watch_together.internal.v1.AuthorityLeaseR\x05lease\"\xc5\x03\n" +
	"\x17ApplyRoomControlRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12,\n" +
	"\x12source_instance_id\x18\x02 \x01(\tR\x10sourceInstanceId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12#\n" +
	"\rconnection_id\x18\x06 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\x12\x10\n" +
	"\x03seq\x18\n" +
	" \x01(\x03R\x03seq\x128\n" +
	"\x18expected_authority_epoch\x18\v \x01(\x03R\x16expectedAuthorityEpoch\x12&\n" +
	"\x0frequested_at_ms\x18\f \x01(\x03R\rrequestedAtMs\"\xb5\x01\n" +
	"\x18ApplyRoomControlResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x12'\n" +
	"\x0fauthority_epoch\x18\x05 \x01(\x03R\x0eauthorityEpoch\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\xb7\x06\n" +
	"\x1cRoomAuthorityInternalService\x12}\n" +
	"\x10GetRoomAuthority\x123.watch_together.internal.v1.GetRoomAuthorityRequest\x1a4.watch_together.internal.v1.GetRoomAuthorityResponse\x12\x83\x01\n" +
	"\x12ClaimRoomAuthority\x125.watch_together.internal.v1.ClaimRoomAuthorityRequest\x1a6.watch_together.internal.v1.ClaimRoomAuthorityResponse\x12\x83\x01\n" +
	"\x12RenewRoomAuthority\x125.watch_together.internal.v1.RenewRoomAuthorityRequest\x1a6.watch_together.internal.v1.RenewRoomAuthorityResponse\x12\x80\x01\n" +
	"\x11BeginRoomRecovery\x124.watch_together.internal.v1.BeginRoomRecoveryRequest\x1a5.watch_together.internal.v1.BeginRoomRecoveryResponse\x12\x89\x01\n" +
	"\x14CompleteRoomRecovery\x127.watch_together.internal.v1.CompleteRoomRecoveryRequest\x1a8.watch_together.internal.v1.CompleteRoomRecoveryResponse\x12}\n" +
	"\x10ApplyRoomControl\x123.watch_together.internal.v1.ApplyRoomControlRequest\x1a4.watch_together.internal.v1.ApplyRoomControlResponseB5Z3watch_together/server/internal/rpcgen/v1;internalv1b\x06proto3"

var (
	file_server_api_internal_v1_authority_proto_rawDescOnce sync.Once
	file_server_api_internal_v1_authority_proto_rawDescData []byte
)

func file_server_api_internal_v1_authority_proto_rawDescGZIP() []byte {
	file_server_api_internal_v1_authority_proto_rawDescOnce.Do(func() {
		file_server_api_internal_v1_authority_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_authority_proto_rawDesc), len(file_server_api_internal_v1_authority_proto_rawDesc)))
	})
	return file_server_api_internal_v1_authority_proto_rawDescData
}

var file_server_api_internal_v1_authority_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_api_internal_v1_authority_proto_goTypes = []any{
	(*AuthorityLease)(nil),               // 0: watch_together.internal.v1.AuthorityLease
	(*GetRoomAuthorityRequest)(nil),      // 1: watch_together.internal.v1.GetRoomAuthorityRequest
	(*GetRoomAuthorityResponse)(nil),     // 2: watch_together.internal.v1.GetRoomAuthorityResponse
	(*ClaimRoomAuthorityRequest)(nil),    // 3: watch_together.internal.v1.ClaimRoomAuthorityRequest
	(*ClaimRoomAuthorityResponse)(nil),   // 4: watch_together.internal.v1.ClaimRoomAuthorityResponse
	(*RenewRoomAuthorityRequest)(nil),    // 5: watch_together.internal.v1.RenewRoomAuthorityRequest
	(*RenewRoomAuthorityResponse)(nil),   // 6: watch_together.internal.v1.RenewRoomAuthorityResponse
	(*BeginRoomRecoveryRequest)(nil),     // 7: watch_together.internal.v1.BeginRoomRecoveryRequest
	(*BeginRoomRecoveryResponse)(nil),    // 8: watch_together.internal.v1.BeginRoomRecoveryResponse
	(*CompleteRoomRecoveryRequest)(nil),  // 9: watch_together.internal.v1.CompleteRoomRecoveryRequest
	(*CompleteRoomRecoveryResponse)(nil), // 10: watch_together.internal.v1.CompleteRoomRecoveryResponse
	(*ApplyRoomControlRequest)(nil),      // 11: watch_together.internal.v1.ApplyRoomControlRequest
	(*ApplyRoomControlResponse)(nil),     // 12: watch_together.internal.v1.ApplyRoomControlResponse
	(*RequestMetadata)(nil),              // 13: watch_together.internal.v1.RequestMetadata
}
var file_server_api_internal_v1_authority_proto_depIdxs = []int32{
	13, // 0: watch_together.internal.v1.GetRoomAuthorityRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	0,  // 1: watch_together.internal.v1.GetRoomAuthorityResponse.lease:type_name -> watch_together.internal.v1.AuthorityLease
	13, // 2: watch_together.internal.v1.ClaimRoomAuthorityRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	0,  // 3: watch_together.internal.v1.ClaimRoomAuthorityResponse.lease:type_name -> watch_together.internal.v1.AuthorityLease
	13, // 4: watch_together.internal.v1.RenewRoomAuthorityRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	0,  // 5: watch_together.internal.v1.RenewRoomAuthorityResponse.lease:type_name -> watch_together.internal.v1.AuthorityLease
	13, // 6: watch_together.internal.v1.BeginRoomRecoveryRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	0,  // 7: watch_together.internal.v1.BeginRoomRecoveryResponse.lease:type_name -> watch_together.internal.v1.AuthorityLease
	13, // 8: watch_together.internal.v1.CompleteRoomRecoveryRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	0,  // 9: watch_together.internal.v1.CompleteRoomRecoveryResponse.lease:type_name -> watch_together.internal.v1.AuthorityLease
	13, // 10: watch_together.internal.v1.ApplyRoomControlRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	1,  // 11: watch_together.internal.v1.RoomAuthorityInternalService.GetRoomAuthority:input_type -> watch_together.internal.v1.GetRoomAuthorityRequest
	3,  // 12: watch_together.internal.v1.RoomAuthorityInternalService.ClaimRoomAuthority:input_type -> watch_together.internal.v1.ClaimRoomAuthorityRequest
	5,  // 13: watch_together.internal.v1.RoomAuthorityInternalService.RenewRoomAuthority:input_type -> watch_together.internal.v1.RenewRoomAuthorityRequest
	7,  // 14: watch_together.internal.v1.RoomAuthorityInternalService.BeginRoomRecovery:input_type -> watch_together.internal.v1.BeginRoomRecoveryRequest
	9,  // 15: watch_together.internal.v1.RoomAuthorityInternalService.CompleteRoomRecovery:input_type -> watch_together.internal.v1.CompleteRoomRecoveryRequest
	11, // 16: watch_together.internal.v1.RoomAuthorityInternalService.ApplyRoomControl:input_type -> watch_together.internal.v1.ApplyRoomControlRequest
	2,  // 17: watch_together.internal.v1.RoomAuthorityInternalService.GetRoomAuthority:output_type -> watch_together.internal.v1.GetRoomAuthorityResponse
	4,  // 18: watch_together.internal.v1.RoomAuthorityInternalService.ClaimRoomAuthority:output_type -> watch_together.internal.v1.ClaimRoomAuthorityResponse
	6,  // 19: watch_together.internal.v1.RoomAuthorityInternalService.RenewRoomAuthority:output_type -> watch_together.internal.v1.RenewRoomAuthorityResponse
	8,  // 20: watch_together.internal.v1.RoomAuthorityInternalService.BeginRoomRecovery:output_type -> watch_together.internal.v1.BeginRoomRecoveryResponse
	10, // 21: watch_together.internal.v1.RoomAuthorityInternalService.CompleteRoomRecovery:output_type -> watch_together.internal.v1.CompleteRoomRecoveryResponse
	12, // 22: watch_together.internal.v1.RoomAuthorityInternalService.ApplyRoomControl:output_type -> watch_together.internal.v1.ApplyRoomControlResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_server_api_internal_v1_authority_proto_init() }
func file_server_api_internal_v1_authority_proto_init() {
	if File_server_api_internal_v1_authority_proto != nil {
		return
	}
	file_server_api_internal_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_authority_proto_rawDesc), len(file_server_api_internal_v1_authority_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_internal_v1_authority_proto_goTypes,
		DependencyIndexes: file_server_api_internal_v1_authority_proto_depIdxs,
		MessageInfos:      file_server_api_internal_v1_authority_proto_msgTypes,
	}.Build()
	File_server_api_internal_v1_authority_proto = out.File
	file_server_api_internal_v1_authority_proto_goTypes = nil
	file_server_api_internal_v1_authority_proto_depIdxs = nil
}
