// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: server/api/internal/v1/home.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHomeSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeSummaryRequest) Reset() {
	*x = GetHomeSummaryRequest{}
	mi := &file_server_api_internal_v1_home_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeSummaryRequest) ProtoMessage() {}

func (x *GetHomeSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_home_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetHomeSummaryRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_home_proto_rawDescGZIP(), []int{0}
}

func (x *GetHomeSummaryRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetHomeSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHomeSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *HomeSummary           `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeSummaryResponse) Reset() {
	*x = GetHomeSummaryResponse{}
	mi := &file_server_api_internal_v1_home_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeSummaryResponse) ProtoMessage() {}

func (x *GetHomeSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_home_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetHomeSummaryResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_home_proto_rawDescGZIP(), []int{1}
}

func (x *GetHomeSummaryResponse) GetSummary() *HomeSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type HomeSummary struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	User             *HomeUserSummary            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	LastWatched      *HomeWatchProgressSummary   `protobuf:"bytes,2,opt,name=last_watched,json=lastWatched,proto3,oneof" json:"last_watched,omitempty"`
	ContinueWatching []*HomeWatchProgressSummary `protobuf:"bytes,3,rep,name=continue_watching,json=continueWatching,proto3" json:"continue_watching,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HomeSummary) Reset() {
	*x = HomeSummary{}
	mi := &file_server_api_internal_v1_home_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeSummary) ProtoMessage() {}

func (x *HomeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_home_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeSummary.ProtoReflect.Descriptor instead.
func (*HomeSummary) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_home_proto_rawDescGZIP(), []int{2}
}

func (x *HomeSummary) GetUser() *HomeUserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HomeSummary) GetLastWatched() *HomeWatchProgressSummary {
	if x != nil {
		return x.LastWatched
	}
	return nil
}

func (x *HomeSummary) GetContinueWatching() []*HomeWatchProgressSummary {
	if x != nil {
		return x.ContinueWatching
	}
	return nil
}

type HomeUserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarSeed    string                 `protobuf:"bytes,2,opt,name=avatar_seed,json=avatarSeed,proto3" json:"avatar_seed,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeUserSummary) Reset() {
	*x = HomeUserSummary{}
	mi := &file_server_api_internal_v1_home_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeUserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeUserSummary) ProtoMessage() {}

func (x *HomeUserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_home_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeUserSummary.ProtoReflect.Descriptor instead.
func (*HomeUserSummary) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_home_proto_rawDescGZIP(), []int{3}
}

func (x *HomeUserSummary) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *HomeUserSummary) GetAvatarSeed() string {
	if x != nil {
		return x.AvatarSeed
	}
	return ""
}

func (x *HomeUserSummary) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

type HomeWatchProgressSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MediaItemId         string                 `protobuf:"bytes,1,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl            *string                `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3,oneof" json:"cover_url,omitempty"`
	LastPositionSeconds int32                  `protobuf:"varint,4,opt,name=last_position_seconds,json=lastPositionSeconds,proto3" json:"last_position_seconds,omitempty"`
	DurationSeconds     int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HomeWatchProgressSummary) Reset() {
	*x = HomeWatchProgressSummary{}
	mi := &file_server_api_internal_v1_home_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeWatchProgressSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeWatchProgressSummary) ProtoMessage() {}

func (x *HomeWatchProgressSummary) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_home_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeWatchProgressSummary.ProtoReflect.Descriptor instead.
func (*HomeWatchProgressSummary) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_home_proto_rawDescGZIP(), []int{4}
}

func (x *HomeWatchProgressSummary) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *HomeWatchProgressSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HomeWatchProgressSummary) GetCoverUrl() string {
	if x != nil && x.CoverUrl != nil {
		return *x.CoverUrl
	}
	return ""
}

func (x *HomeWatchProgressSummary) GetLastPositionSeconds() int32 {
	if x != nil {
		return x.LastPositionSeconds
	}
	return 0
}

func (x *HomeWatchProgressSummary) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

var File_server_api_internal_v1_home_proto protoreflect.FileDescriptor

const file_server_api_internal_v1_home_proto_rawDesc = "" +
	"\n" +
	"!server/api/internal/v1/home.proto\x12\x1awatch_together.internal.v1\x1a#server/api/internal/v1/common.proto\"y\n" +
	"\x15GetHomeSummaryRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"[\n" +
	"\x16GetHomeSummaryResponse\x12A\n" +
	"\asummary\x18\x01 \x01(\v2'.watch_together.internal.v1.HomeSummaryR\asummary\"\xa0\x02\n" +
	"\vHomeSummary\x12?\n" +
	"\x04user\x18\x01 \x01(\v2+.watch_together.internal.v1.HomeUserSummaryR\x04user\x12\\\n" +
	"\flast_watched\x18\x02 \x01(\v24.watch_together.internal.v1.HomeWatchProgressSummaryH\x00R\vlastWatched\x88\x01\x01\x12a\n" +
	"\x11continue_watching\x18\x03 \x03(\v24.watch_together.internal.v1.HomeWatchProgressSummaryR\x10continueWatchingB\x0f\n" +
	"\r_last_watched\"\x81\x01\n" +
	"\x0fHomeUserSummary\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1f\n" +
	"\vavatar_seed\x18\x02 \x01(\tR\n" +
	"avatarSeed\x12\"\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tH\x00R\tavatarUrl\x88\x01\x01B\r\n" +
	"\v_avatar_url\"\xe3\x01\n" +
	"\x18HomeWatchProgressSummary\x12\"\n" +
	"\rmedia_item_id\x18\x01 \x01(\tR\vmediaItemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\tcover_url\x18\x03 \x01(\tH\x00R\bcoverUrl\x88\x01\x01\x122\n" +
	"\x15last_position_seconds\x18\x04 \x01(\x05R\x13lastPositionSeconds\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSecondsB\f\n" +
	"\n" +
	"_cover_url2\x99\x01\n" +
	"\x1eHomeCompositionInternalService\x12w\n" +
	"\x0eGetHomeSummary\x121.watch_together.internal.v1.GetHomeSummaryRequest\x1a2.watch_together.internal.v1.GetHomeSummaryResponseB5Z3watch_together/server/internal/rpcgen/v1;internalv1b\x06proto3"

var (
	file_server_api_internal_v1_home_proto_rawDescOnce sync.Once
	file_server_api_internal_v1_home_proto_rawDescData []byte
)

func file_server_api_internal_v1_home_proto_rawDescGZIP() []byte {
	file_server_api_internal_v1_home_proto_rawDescOnce.Do(func() {
		file_server_api_internal_v1_home_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_home_proto_rawDesc), len(file_server_api_internal_v1_home_proto_rawDesc)))
	})
	return file_server_api_internal_v1_home_proto_rawDescData
}

var file_server_api_internal_v1_home_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_server_api_internal_v1_home_proto_goTypes = []any{
	(*GetHomeSummaryRequest)(nil),    // 0: watch_together.internal.v1.GetHomeSummaryRequest
	(*GetHomeSummaryResponse)(nil),   // 1: watch_together.internal.v1.GetHomeSummaryResponse
	(*HomeSummary)(nil),              // 2: watch_together.internal.v1.HomeSummary
	(*HomeUserSummary)(nil),          // 3: watch_together.internal.v1.HomeUserSummary
	(*HomeWatchProgressSummary)(nil), // 4: watch_together.internal.v1.HomeWatchProgressSummary
	(*RequestMetadata)(nil),          // 5: watch_together.internal.v1.RequestMetadata
}
var file_server_api_internal_v1_home_proto_depIdxs = []int32{
	5, // 0: watch_together.internal.v1.GetHomeSummaryRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	2, // 1: watch_together.internal.v1.GetHomeSummaryResponse.summary:type_name -> watch_together.internal.v1.HomeSummary
	3, // 2: watch_together.internal.v1.HomeSummary.user:type_name -> watch_together.internal.v1.HomeUserSummary
	4, // 3: watch_together.internal.v1.HomeSummary.last_watched:type_name -> watch_together.internal.v1.HomeWatchProgressSummary
	4, // 4: watch_together.internal.v1.HomeSummary.continue_watching:type_name -> watch_together.internal.v1.HomeWatchProgressSummary
	0, // 5: watch_together.internal.v1.HomeCompositionInternalService.GetHomeSummary:input_type -> watch_together.internal.v1.GetHomeSummaryRequest
	1, // 6: watch_together.internal.v1.HomeCompositionInternalService.GetHomeSummary:output_type -> watch_together.internal.v1.GetHomeSummaryResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_server_api_internal_v1_home_proto_init() }
func file_server_api_internal_v1_home_proto_init() {
	if File_server_api_internal_v1_home_proto != nil {
		return
	}
	file_server_api_internal_v1_common_proto_init()
	file_server_api_internal_v1_home_proto_msgTypes[2].OneofWrappers = []any{}
	file_server_api_internal_v1_home_proto_msgTypes[3].OneofWrappers = []any{}
	file_server_api_internal_v1_home_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_home_proto_rawDesc), len(file_server_api_internal_v1_home_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_internal_v1_home_proto_goTypes,
		DependencyIndexes: file_server_api_internal_v1_home_proto_depIdxs,
		MessageInfos:      file_server_api_internal_v1_home_proto_msgTypes,
	}.Build()
	File_server_api_internal_v1_home_proto = out.File
	file_server_api_internal_v1_home_proto_goTypes = nil
	file_server_api_internal_v1_home_proto_depIdxs = nil
}
