// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: server/api/internal/v1/identity.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *IdentityUser          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetUser() *IdentityUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *IdentityUser          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUser() *IdentityUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenRequest) Reset() {
	*x = VerifyAccessTokenRequest{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenRequest) ProtoMessage() {}

func (x *VerifyAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyAccessTokenRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VerifyAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenResponse) Reset() {
	*x = VerifyAccessTokenResponse{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenResponse) ProtoMessage() {}

func (x *VerifyAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyAccessTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserProfileRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *IdentityUser          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserProfileResponse) GetUser() *IdentityUser {
	if x != nil {
		return x.User
	}
	return nil
}

type IdentityUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarSeed    string                 `protobuf:"bytes,4,opt,name=avatar_seed,json=avatarSeed,proto3" json:"avatar_seed,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Bio           *string                `protobuf:"bytes,6,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityUser) Reset() {
	*x = IdentityUser{}
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityUser) ProtoMessage() {}

func (x *IdentityUser) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityUser.ProtoReflect.Descriptor instead.
func (*IdentityUser) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *IdentityUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *IdentityUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *IdentityUser) GetAvatarSeed() string {
	if x != nil {
		return x.AvatarSeed
	}
	return ""
}

func (x *IdentityUser) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *IdentityUser) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

var File_server_api_internal_v1_identity_proto protoreflect.FileDescriptor

const file_server_api_internal_v1_identity_proto_rawDesc = "" +
	"\n" +
	"%server/api/internal/v1/identity.proto\x12\x1awatch_together.internal.v1\x1a#server/api/internal/v1/common.proto\"\xac\x01\n" +
	"\x0fRegisterRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"\x8d\x01\n" +
	"\fLoginRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"s\n" +
	"\x10RegisterResponse\x12<\n" +
	"\x04user\x18\x01 \x01(\v2(.watch_together.internal.v1.IdentityUserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"p\n" +
	"\rLoginResponse\x12<\n" +
	"\x04user\x18\x01 \x01(\v2(.watch_together.internal.v1.IdentityUserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"\x86\x01\n" +
	"\x18VerifyAccessTokenRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"4\n" +
	"\x19VerifyAccessTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"y\n" +
	"\x15GetUserProfileRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"V\n" +
	"\x16GetUserProfileResponse\x12<\n" +
	"\x04user\x18\x01 \x01(\v2(.watch_together.internal.v1.IdentityUserR\x04user\"\xc7\x01\n" +
	"\fIdentityUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1f\n" +
	"\vavatar_seed\x18\x04 \x01(\tR\n" +
	"avatarSeed\x12\"\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\x06 \x01(\tH\x01R\x03bio\x88\x01\x01B\r\n" +
	"\v_avatar_urlB\x06\n" +
	"\x04_bio2\xda\x03\n" +
	"\x17IdentityInternalService\x12e\n" +
	"\bRegister\x12+.watch_together.internal.v1.RegisterRequest\x1a,.watch_together.internal.v1.RegisterResponse\x12\\\n" +
	"\x05Login\x12(.watch_together.internal.v1.LoginRequest\x1a).watch_together.internal.v1.LoginResponse\x12\x80\x01\n" +
	"\x11VerifyAccessToken\x124.watch_together.internal.v1.VerifyAccessTokenRequest\x1a5.watch_together.internal.v1.VerifyAccessTokenResponse\x12w\n" +
	"\x0eGetUserProfile\x121.watch_together.internal.v1.GetUserProfileRequest\x1a2.watch_together.internal.v1.GetUserProfileResponseB5Z3watch_together/server/internal/rpcgen/v1;internalv1b\x06proto3"

var (
	file_server_api_internal_v1_identity_proto_rawDescOnce sync.Once
	file_server_api_internal_v1_identity_proto_rawDescData []byte
)

func file_server_api_internal_v1_identity_proto_rawDescGZIP() []byte {
	file_server_api_internal_v1_identity_proto_rawDescOnce.Do(func() {
		file_server_api_internal_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_identity_proto_rawDesc), len(file_server_api_internal_v1_identity_proto_rawDesc)))
	})
	return file_server_api_internal_v1_identity_proto_rawDescData
}

var file_server_api_internal_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_server_api_internal_v1_identity_proto_goTypes = []any{
	(*RegisterRequest)(nil),           // 0: watch_together.internal.v1.RegisterRequest
	(*LoginRequest)(nil),              // 1: watch_together.internal.v1.LoginRequest
	(*RegisterResponse)(nil),          // 2: watch_together.internal.v1.RegisterResponse
	(*LoginResponse)(nil),             // 3: watch_together.internal.v1.LoginResponse
	(*VerifyAccessTokenRequest)(nil),  // 4: watch_together.internal.v1.VerifyAccessTokenRequest
	(*VerifyAccessTokenResponse)(nil), // 5: watch_together.internal.v1.VerifyAccessTokenResponse
	(*GetUserProfileRequest)(nil),     // 6: watch_together.internal.v1.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),    // 7: watch_together.internal.v1.GetUserProfileResponse
	(*IdentityUser)(nil),              // 8: watch_together.internal.v1.IdentityUser
	(*RequestMetadata)(nil),           // 9: watch_together.internal.v1.RequestMetadata
}
var file_server_api_internal_v1_identity_proto_depIdxs = []int32{
	9,  // 0: watch_together.internal.v1.RegisterRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	9,  // 1: watch_together.internal.v1.LoginRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	8,  // 2: watch_together.internal.v1.RegisterResponse.user:type_name -> watch_together.internal.v1.IdentityUser
	8,  // 3: watch_together.internal.v1.LoginResponse.user:type_name -> watch_together.internal.v1.IdentityUser
	9,  // 4: watch_together.internal.v1.VerifyAccessTokenRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	9,  // 5: watch_together.internal.v1.GetUserProfileRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	8,  // 6: watch_together.internal.v1.GetUserProfileResponse.user:type_name -> watch_together.internal.v1.IdentityUser
	0,  // 7: watch_together.internal.v1.IdentityInternalService.Register:input_type -> watch_together.internal.v1.RegisterRequest
	1,  // 8: watch_together.internal.v1.IdentityInternalService.Login:input_type -> watch_together.internal.v1.LoginRequest
	4,  // 9: watch_together.internal.v1.IdentityInternalService.VerifyAccessToken:input_type -> watch_together.internal.v1.VerifyAccessTokenRequest
	6,  // 10: watch_together.internal.v1.IdentityInternalService.GetUserProfile:input_type -> watch_together.internal.v1.GetUserProfileRequest
	2,  // 11: watch_together.internal.v1.IdentityInternalService.Register:output_type -> watch_together.internal.v1.RegisterResponse
	3,  // 12: watch_together.internal.v1.IdentityInternalService.Login:output_type -> watch_together.internal.v1.LoginResponse
	5,  // 13: watch_together.internal.v1.IdentityInternalService.VerifyAccessToken:output_type -> watch_together.internal.v1.VerifyAccessTokenResponse
	7,  // 14: watch_together.internal.v1.IdentityInternalService.GetUserProfile:output_type -> watch_together.internal.v1.GetUserProfileResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_server_api_internal_v1_identity_proto_init() }
func file_server_api_internal_v1_identity_proto_init() {
	if File_server_api_internal_v1_identity_proto != nil {
		return
	}
	file_server_api_internal_v1_common_proto_init()
	file_server_api_internal_v1_identity_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_identity_proto_rawDesc), len(file_server_api_internal_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_internal_v1_identity_proto_goTypes,
		DependencyIndexes: file_server_api_internal_v1_identity_proto_depIdxs,
		MessageInfos:      file_server_api_internal_v1_identity_proto_msgTypes,
	}.Build()
	File_server_api_internal_v1_identity_proto = out.File
	file_server_api_internal_v1_identity_proto_goTypes = nil
	file_server_api_internal_v1_identity_proto_depIdxs = nil
}
