// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: server/api/internal/v1/media.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AllLimit      int32                  `protobuf:"varint,2,opt,name=all_limit,json=allLimit,proto3" json:"all_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *ListTagsRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListTagsRequest) GetAllLimit() int32 {
	if x != nil {
		return x.AllLimit
	}
	return 0
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeaturedTags  []*MediaTag            `protobuf:"bytes,1,rep,name=featured_tags,json=featuredTags,proto3" json:"featured_tags,omitempty"`
	AllTags       []*MediaTag            `protobuf:"bytes,2,rep,name=all_tags,json=allTags,proto3" json:"all_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *ListTagsResponse) GetFeaturedTags() []*MediaTag {
	if x != nil {
		return x.FeaturedTags
	}
	return nil
}

func (x *ListTagsResponse) GetAllTags() []*MediaTag {
	if x != nil {
		return x.AllTags
	}
	return nil
}

type SearchItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Params        *MediaSearchParams     `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsRequest) Reset() {
	*x = SearchItemsRequest{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsRequest) ProtoMessage() {}

func (x *SearchItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsRequest.ProtoReflect.Descriptor instead.
func (*SearchItemsRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *SearchItemsRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchItemsRequest) GetParams() *MediaSearchParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type SearchItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MediaItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsResponse) Reset() {
	*x = SearchItemsResponse{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsResponse) ProtoMessage() {}

func (x *SearchItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsResponse.ProtoReflect.Descriptor instead.
func (*SearchItemsResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *SearchItemsResponse) GetItems() []*MediaItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetPlaybackItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EpisodeId     string                 `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaybackItemRequest) Reset() {
	*x = GetPlaybackItemRequest{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaybackItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaybackItemRequest) ProtoMessage() {}

func (x *GetPlaybackItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaybackItemRequest.ProtoReflect.Descriptor instead.
func (*GetPlaybackItemRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlaybackItemRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetPlaybackItemRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

type GetPlaybackItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *PlaybackItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaybackItemResponse) Reset() {
	*x = GetPlaybackItemResponse{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaybackItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaybackItemResponse) ProtoMessage() {}

func (x *GetPlaybackItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaybackItemResponse.ProtoReflect.Descriptor instead.
func (*GetPlaybackItemResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlaybackItemResponse) GetItem() *PlaybackItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type AuthorizePlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EpisodeId     string                 `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	AssetPath     string                 `protobuf:"bytes,3,opt,name=asset_path,json=assetPath,proto3" json:"asset_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePlaybackRequest) Reset() {
	*x = AuthorizePlaybackRequest{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePlaybackRequest) ProtoMessage() {}

func (x *AuthorizePlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePlaybackRequest.ProtoReflect.Descriptor instead.
func (*AuthorizePlaybackRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizePlaybackRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuthorizePlaybackRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *AuthorizePlaybackRequest) GetAssetPath() string {
	if x != nil {
		return x.AssetPath
	}
	return ""
}

type AuthorizePlaybackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePlaybackResponse) Reset() {
	*x = AuthorizePlaybackResponse{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePlaybackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePlaybackResponse) ProtoMessage() {}

func (x *AuthorizePlaybackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePlaybackResponse.ProtoReflect.Descriptor instead.
func (*AuthorizePlaybackResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizePlaybackResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type GetEpisodeDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EpisodeId     string                 `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpisodeDetailRequest) Reset() {
	*x = GetEpisodeDetailRequest{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpisodeDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpisodeDetailRequest) ProtoMessage() {}

func (x *GetEpisodeDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpisodeDetailRequest.ProtoReflect.Descriptor instead.
func (*GetEpisodeDetailRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{8}
}

func (x *GetEpisodeDetailRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetEpisodeDetailRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

type GetEpisodeDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episode       *EpisodeDetail         `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpisodeDetailResponse) Reset() {
	*x = GetEpisodeDetailResponse{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpisodeDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpisodeDetailResponse) ProtoMessage() {}

func (x *GetEpisodeDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpisodeDetailResponse.ProtoReflect.Descriptor instead.
func (*GetEpisodeDetailResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetEpisodeDetailResponse) GetEpisode() *EpisodeDetail {
	if x != nil {
		return x.Episode
	}
	return nil
}

type ValidatePlayableEpisodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EpisodeId     string                 `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePlayableEpisodeRequest) Reset() {
	*x = ValidatePlayableEpisodeRequest{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePlayableEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePlayableEpisodeRequest) ProtoMessage() {}

func (x *ValidatePlayableEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePlayableEpisodeRequest.ProtoReflect.Descriptor instead.
func (*ValidatePlayableEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{10}
}

func (x *ValidatePlayableEpisodeRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ValidatePlayableEpisodeRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

type ValidatePlayableEpisodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	Playable      bool                   `protobuf:"varint,2,opt,name=playable,proto3" json:"playable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePlayableEpisodeResponse) Reset() {
	*x = ValidatePlayableEpisodeResponse{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePlayableEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePlayableEpisodeResponse) ProtoMessage() {}

func (x *ValidatePlayableEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePlayableEpisodeResponse.ProtoReflect.Descriptor instead.
func (*ValidatePlayableEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{11}
}

func (x *ValidatePlayableEpisodeResponse) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *ValidatePlayableEpisodeResponse) GetPlayable() bool {
	if x != nil {
		return x.Playable
	}
	return false
}

type BatchGetEpisodeSummariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EpisodeIds    []string               `protobuf:"bytes,2,rep,name=episode_ids,json=episodeIds,proto3" json:"episode_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetEpisodeSummariesRequest) Reset() {
	*x = BatchGetEpisodeSummariesRequest{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetEpisodeSummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetEpisodeSummariesRequest) ProtoMessage() {}

func (x *BatchGetEpisodeSummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetEpisodeSummariesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetEpisodeSummariesRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetEpisodeSummariesRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BatchGetEpisodeSummariesRequest) GetEpisodeIds() []string {
	if x != nil {
		return x.EpisodeIds
	}
	return nil
}

type BatchGetEpisodeSummariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episodes      []*EpisodeSummary      `protobuf:"bytes,1,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetEpisodeSummariesResponse) Reset() {
	*x = BatchGetEpisodeSummariesResponse{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetEpisodeSummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetEpisodeSummariesResponse) ProtoMessage() {}

func (x *BatchGetEpisodeSummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetEpisodeSummariesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetEpisodeSummariesResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetEpisodeSummariesResponse) GetEpisodes() []*EpisodeSummary {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type MediaTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaTag) Reset() {
	*x = MediaTag{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaTag) ProtoMessage() {}

func (x *MediaTag) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaTag.ProtoReflect.Descriptor instead.
func (*MediaTag) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{14}
}

func (x *MediaTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaTag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MediaTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MediaItemTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemTag) Reset() {
	*x = MediaItemTag{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemTag) ProtoMessage() {}

func (x *MediaItemTag) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemTag.ProtoReflect.Descriptor instead.
func (*MediaItemTag) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{15}
}

func (x *MediaItemTag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MediaItemTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MediaItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      *string                `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CoverUrl      *string                `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3,oneof" json:"cover_url,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,6,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	DurationMs    *int64                 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	SeasonLabel   *string                `protobuf:"bytes,8,opt,name=season_label,json=seasonLabel,proto3,oneof" json:"season_label,omitempty"`
	EpisodeLabel  *string                `protobuf:"bytes,9,opt,name=episode_label,json=episodeLabel,proto3,oneof" json:"episode_label,omitempty"`
	Tags          []*MediaItemTag        `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItem.ProtoReflect.Descriptor instead.
func (*MediaItem) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{16}
}

func (x *MediaItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MediaItem) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *MediaItem) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *MediaItem) GetCoverUrl() string {
	if x != nil && x.CoverUrl != nil {
		return *x.CoverUrl
	}
	return ""
}

func (x *MediaItem) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *MediaItem) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *MediaItem) GetSeasonLabel() string {
	if x != nil && x.SeasonLabel != nil {
		return *x.SeasonLabel
	}
	return ""
}

func (x *MediaItem) GetEpisodeLabel() string {
	if x != nil && x.EpisodeLabel != nil {
		return *x.EpisodeLabel
	}
	return ""
}

func (x *MediaItem) GetTags() []*MediaItemTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PlaybackItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackItem) Reset() {
	*x = PlaybackItem{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackItem) ProtoMessage() {}

func (x *PlaybackItem) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackItem.ProtoReflect.Descriptor instead.
func (*PlaybackItem) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{17}
}

func (x *PlaybackItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlaybackItem) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

type EpisodeDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      *string                `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,4,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	DurationMs    *int64                 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	SeasonLabel   *string                `protobuf:"bytes,6,opt,name=season_label,json=seasonLabel,proto3,oneof" json:"season_label,omitempty"`
	EpisodeLabel  *string                `protobuf:"bytes,7,opt,name=episode_label,json=episodeLabel,proto3,oneof" json:"episode_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeDetail) Reset() {
	*x = EpisodeDetail{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeDetail) ProtoMessage() {}

func (x *EpisodeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeDetail.ProtoReflect.Descriptor instead.
func (*EpisodeDetail) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{18}
}

func (x *EpisodeDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EpisodeDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EpisodeDetail) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *EpisodeDetail) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *EpisodeDetail) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *EpisodeDetail) GetSeasonLabel() string {
	if x != nil && x.SeasonLabel != nil {
		return *x.SeasonLabel
	}
	return ""
}

func (x *EpisodeDetail) GetEpisodeLabel() string {
	if x != nil && x.EpisodeLabel != nil {
		return *x.EpisodeLabel
	}
	return ""
}

type EpisodeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      *string                `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3,oneof" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeSummary) Reset() {
	*x = EpisodeSummary{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeSummary) ProtoMessage() {}

func (x *EpisodeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeSummary.ProtoReflect.Descriptor instead.
func (*EpisodeSummary) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{19}
}

func (x *EpisodeSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EpisodeSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EpisodeSummary) GetCoverUrl() string {
	if x != nil && x.CoverUrl != nil {
		return *x.CoverUrl
	}
	return ""
}

type MediaSearchParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSearchParams) Reset() {
	*x = MediaSearchParams{}
	mi := &file_server_api_internal_v1_media_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSearchParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSearchParams) ProtoMessage() {}

func (x *MediaSearchParams) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_media_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSearchParams.ProtoReflect.Descriptor instead.
func (*MediaSearchParams) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_media_proto_rawDescGZIP(), []int{20}
}

func (x *MediaSearchParams) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MediaSearchParams) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MediaSearchParams) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MediaSearchParams) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_server_api_internal_v1_media_proto protoreflect.FileDescriptor

const file_server_api_internal_v1_media_proto_rawDesc = "" +
	"\n" +
	"\"server/api/internal/v1/media.proto\x12\x1awatch_together.internal.v1\x1a#server/api/internal/v1/common.proto\"w\n" +
	"\x0fListTagsRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\tall_limit\x18\x02 \x01(\x05R\ballLimit\"\x9e\x01\n" +
	"\x10ListTagsResponse\x12I\n" +
	"\rfeatured_tags\x18\x01 \x03(\v2$.watch_together.internal.v1.MediaTagR\ffeaturedTags\x12?\n" +
	"\ball_tags\x18\x02 \x03(\v2$.watch_together.internal.v1.MediaTagR\aallTags\"\xa4\x01\n" +
	"\x12SearchItemsRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12E\n" +
	"\x06params\x18\x02 \x01(\v2-.watch_together.internal.v1.MediaSearchParamsR\x06params\"R\n" +
	"\x13SearchItemsResponse\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.watch_together.internal.v1.MediaItemR\x05items\"\x80\x01\n" +
	"\x16GetPlaybackItemRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tR\tepisodeId\"W\n" +
	"\x17GetPlaybackItemResponse\x12<\n" +
	"\x04item\x18\x01 \x01(\v2(.watch_together.internal.v1.PlaybackItemR\x04item\"\xa1\x01\n" +
	"\x18AuthorizePlaybackRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tR\tepisodeId\x12\x1d\n" +
	"\n" +
	"asset_path\x18\x03 \x01(\tR\tassetPath\";\n" +
	"\x19AuthorizePlaybackResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\"\x81\x01\n" +
	"\x17GetEpisodeDetailRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tR\tepisodeId\"_\n" +
	"\x18GetEpisodeDetailResponse\x12C\n" +
	"\aepisode\x18\x01 \x01(\v2).watch_together.internal.v1.EpisodeDetailR\aepisode\"\x88\x01\n" +
	"\x1eValidatePlayableEpisodeRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tR\tepisodeId\"\\\n" +
	"\x1fValidatePlayableEpisodeResponse\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x1a\n" +
	"\bplayable\x18\x02 \x01(\bR\bplayable\"\x8b\x01\n" +
	"\x1fBatchGetEpisodeSummariesRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1f\n" +
	"\vepisode_ids\x18\x02 \x03(\tR\n" +
	"episodeIds\"j\n" +
	" BatchGetEpisodeSummariesResponse\x12F\n" +
	"\bepisodes\x18\x01 \x03(\v2*.watch_together.internal.v1.EpisodeSummaryR\bepisodes\"B\n" +
	"\bMediaTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"6\n" +
	"\fMediaItemTag\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xcc\x03\n" +
	"\tMediaItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\bsubtitle\x18\x03 \x01(\tH\x00R\bsubtitle\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\tcover_url\x18\x05 \x01(\tH\x02R\bcoverUrl\x88\x01\x01\x12\x1b\n" +
	"\tmedia_url\x18\x06 \x01(\tR\bmediaUrl\x12$\n" +
	"\vduration_ms\x18\a \x01(\x03H\x03R\n" +
	"durationMs\x88\x01\x01\x12&\n" +
	"\fseason_label\x18\b \x01(\tH\x04R\vseasonLabel\x88\x01\x01\x12(\n" +
	"\repisode_label\x18\t \x01(\tH\x05R\fepisodeLabel\x88\x01\x01\x12<\n" +
	"\x04tags\x18\n" +
	" \x03(\v2(.watch_together.internal.v1.MediaItemTagR\x04tagsB\v\n" +
	"\t_subtitleB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_cover_urlB\x0e\n" +
	"\f_duration_msB\x0f\n" +
	"\r_season_labelB\x10\n" +
	"\x0e_episode_label\";\n" +
	"\fPlaybackItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\"\xab\x02\n" +
	"\rEpisodeDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\bsubtitle\x18\x03 \x01(\tH\x00R\bsubtitle\x88\x01\x01\x12\x1b\n" +
	"\tmedia_url\x18\x04 \x01(\tR\bmediaUrl\x12$\n" +
	"\vduration_ms\x18\x05 \x01(\x03H\x01R\n" +
	"durationMs\x88\x01\x01\x12&\n" +
	"\fseason_label\x18\x06 \x01(\tH\x02R\vseasonLabel\x88\x01\x01\x12(\n" +
	"\repisode_label\x18\a \x01(\tH\x03R\fepisodeLabel\x88\x01\x01B\v\n" +
	"\t_subtitleB\x0e\n" +
	"\f_duration_msB\x0f\n" +
	"\r_season_labelB\x10\n" +
	"\x0e_episode_label\"f\n" +
	"\x0eEpisodeSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\tcover_url\x18\x03 \x01(\tH\x00R\bcoverUrl\x88\x01\x01B\f\n" +
	"\n" +
	"_cover_url\"i\n" +
	"\x11MediaSearchParams\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset2\x98\a\n" +
	"\x14MediaInternalService\x12e\n" +
	"\bListTags\x12+.watch_together.internal.v1.ListTagsRequest\x1a,.watch_together.internal.v1.ListTagsResponse\x12n\n" +
	"\vSearchItems\x12..watch_together.internal.v1.SearchItemsRequest\x1a/.watch_together.internal.v1.SearchItemsResponse\x12z\n" +
	"\x0fGetPlaybackItem\x122.watch_together.internal.v1.GetPlaybackItemRequest\x1a3.watch_together.internal.v1.GetPlaybackItemResponse\x12\x80\x01\n" +
	"\x11AuthorizePlayback\x124.watch_together.internal.v1.AuthorizePlaybackRequest\x1a5.watch_together.internal.v1.AuthorizePlaybackResponse\x12}\n" +
	"\x10GetEpisodeDetail\x123.watch_together.internal.v1.GetEpisodeDetailRequest\x1a4.watch_together.internal.v1.GetEpisodeDetailResponse\x12\x92\x01\n" +
	"\x17ValidatePlayableEpisode\x12:.watch_together.internal.v1.ValidatePlayableEpisodeRequest\x1a;.watch_together.internal.v1.ValidatePlayableEpisodeResponse\x12\x95\x01\n" +
	"\x18BatchGetEpisodeSummaries\x12;.watch_together.internal.v1.BatchGetEpisodeSummariesRequest\x1a<.watch_together.internal.v1.BatchGetEpisodeSummariesResponseB5Z3watch_together/server/internal/rpcgen/v1;internalv1b\x06proto3"

var (
	file_server_api_internal_v1_media_proto_rawDescOnce sync.Once
	file_server_api_internal_v1_media_proto_rawDescData []byte
)

func file_server_api_internal_v1_media_proto_rawDescGZIP() []byte {
	file_server_api_internal_v1_media_proto_rawDescOnce.Do(func() {
		file_server_api_internal_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_media_proto_rawDesc), len(file_server_api_internal_v1_media_proto_rawDesc)))
	})
	return file_server_api_internal_v1_media_proto_rawDescData
}

var file_server_api_internal_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_server_api_internal_v1_media_proto_goTypes = []any{
	(*ListTagsRequest)(nil),                  // 0: watch_together.internal.v1.ListTagsRequest
	(*ListTagsResponse)(nil),                 // 1: watch_together.internal.v1.ListTagsResponse
	(*SearchItemsRequest)(nil),               // 2: watch_together.internal.v1.SearchItemsRequest
	(*SearchItemsResponse)(nil),              // 3: watch_together.internal.v1.SearchItemsResponse
	(*GetPlaybackItemRequest)(nil),           // 4: watch_together.internal.v1.GetPlaybackItemRequest
	(*GetPlaybackItemResponse)(nil),          // 5: watch_together.internal.v1.GetPlaybackItemResponse
	(*AuthorizePlaybackRequest)(nil),         // 6: watch_together.internal.v1.AuthorizePlaybackRequest
	(*AuthorizePlaybackResponse)(nil),        // 7: watch_together.internal.v1.AuthorizePlaybackResponse
	(*GetEpisodeDetailRequest)(nil),          // 8: watch_together.internal.v1.GetEpisodeDetailRequest
	(*GetEpisodeDetailResponse)(nil),         // 9: watch_together.internal.v1.GetEpisodeDetailResponse
	(*ValidatePlayableEpisodeRequest)(nil),   // 10: watch_together.internal.v1.ValidatePlayableEpisodeRequest
	(*ValidatePlayableEpisodeResponse)(nil),  // 11: watch_together.internal.v1.ValidatePlayableEpisodeResponse
	(*BatchGetEpisodeSummariesRequest)(nil),  // 12: watch_together.internal.v1.BatchGetEpisodeSummariesRequest
	(*BatchGetEpisodeSummariesResponse)(nil), // 13: watch_together.internal.v1.BatchGetEpisodeSummariesResponse
	(*MediaTag)(nil),                         // 14: watch_together.internal.v1.MediaTag
	(*MediaItemTag)(nil),                     // 15: watch_together.internal.v1.MediaItemTag
	(*MediaItem)(nil),                        // 16: watch_together.internal.v1.MediaItem
	(*PlaybackItem)(nil),                     // 17: watch_together.internal.v1.PlaybackItem
	(*EpisodeDetail)(nil),                    // 18: watch_together.internal.v1.EpisodeDetail
	(*EpisodeSummary)(nil),                   // 19: watch_together.internal.v1.EpisodeSummary
	(*MediaSearchParams)(nil),                // 20: watch_together.internal.v1.MediaSearchParams
	(*RequestMetadata)(nil),                  // 21: watch_together.internal.v1.RequestMetadata
}
var file_server_api_internal_v1_media_proto_depIdxs = []int32{
	21, // 0: watch_together.internal.v1.ListTagsRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	14, // 1: watch_together.internal.v1.ListTagsResponse.featured_tags:type_name -> watch_together.internal.v1.MediaTag
	14, // 2: watch_together.internal.v1.ListTagsResponse.all_tags:type_name -> watch_together.internal.v1.MediaTag
	21, // 3: watch_together.internal.v1.SearchItemsRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	20, // 4: watch_together.internal.v1.SearchItemsRequest.params:type_name -> watch_together.internal.v1.MediaSearchParams
	16, // 5: watch_together.internal.v1.SearchItemsResponse.items:type_name -> watch_together.internal.v1.MediaItem
	21, // 6: watch_together.internal.v1.GetPlaybackItemRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	17, // 7: watch_together.internal.v1.GetPlaybackItemResponse.item:type_name -> watch_together.internal.v1.PlaybackItem
	21, // 8: watch_together.internal.v1.AuthorizePlaybackRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	21, // 9: watch_together.internal.v1.GetEpisodeDetailRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	18, // 10: watch_together.internal.v1.GetEpisodeDetailResponse.episode:type_name -> watch_together.internal.v1.EpisodeDetail
	21, // 11: watch_together.internal.v1.ValidatePlayableEpisodeRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	21, // 12: watch_together.internal.v1.BatchGetEpisodeSummariesRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	19, // 13: watch_together.internal.v1.BatchGetEpisodeSummariesResponse.episodes:type_name -> watch_together.internal.v1.EpisodeSummary
	15, // 14: watch_together.internal.v1.MediaItem.tags:type_name -> watch_together.internal.v1.MediaItemTag
	0,  // 15: watch_together.internal.v1.MediaInternalService.ListTags:input_type -> watch_together.internal.v1.ListTagsRequest
	2,  // 16: watch_together.internal.v1.MediaInternalService.SearchItems:input_type -> watch_together.internal.v1.SearchItemsRequest
	4,  // 17: watch_together.internal.v1.MediaInternalService.GetPlaybackItem:input_type -> watch_together.internal.v1.GetPlaybackItemRequest
	6,  // 18: watch_together.internal.v1.MediaInternalService.AuthorizePlayback:input_type -> watch_together.internal.v1.AuthorizePlaybackRequest
	8,  // 19: watch_together.internal.v1.MediaInternalService.GetEpisodeDetail:input_type -> watch_together.internal.v1.GetEpisodeDetailRequest
	10, // 20: watch_together.internal.v1.MediaInternalService.ValidatePlayableEpisode:input_type -> watch_together.internal.v1.ValidatePlayableEpisodeRequest
	12, // 21: watch_together.internal.v1.MediaInternalService.BatchGetEpisodeSummaries:input_type -> watch_together.internal.v1.BatchGetEpisodeSummariesRequest
	1,  // 22: watch_together.internal.v1.MediaInternalService.ListTags:output_type -> watch_together.internal.v1.ListTagsResponse
	3,  // 23: watch_together.internal.v1.MediaInternalService.SearchItems:output_type -> watch_together.internal.v1.SearchItemsResponse
	5,  // 24: watch_together.internal.v1.MediaInternalService.GetPlaybackItem:output_type -> watch_together.internal.v1.GetPlaybackItemResponse
	7,  // 25: watch_together.internal.v1.MediaInternalService.AuthorizePlayback:output_type -> watch_together.internal.v1.AuthorizePlaybackResponse
	9,  // 26: watch_together.internal.v1.MediaInternalService.GetEpisodeDetail:output_type -> watch_together.internal.v1.GetEpisodeDetailResponse
	11, // 27: watch_together.internal.v1.MediaInternalService.ValidatePlayableEpisode:output_type -> watch_together.internal.v1.ValidatePlayableEpisodeResponse
	13, // 28: watch_together.internal.v1.MediaInternalService.BatchGetEpisodeSummaries:output_type -> watch_together.internal.v1.BatchGetEpisodeSummariesResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_server_api_internal_v1_media_proto_init() }
func file_server_api_internal_v1_media_proto_init() {
	if File_server_api_internal_v1_media_proto != nil {
		return
	}
	file_server_api_internal_v1_common_proto_init()
	file_server_api_internal_v1_media_proto_msgTypes[16].OneofWrappers = []any{}
	file_server_api_internal_v1_media_proto_msgTypes[18].OneofWrappers = []any{}
	file_server_api_internal_v1_media_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_media_proto_rawDesc), len(file_server_api_internal_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_internal_v1_media_proto_goTypes,
		DependencyIndexes: file_server_api_internal_v1_media_proto_depIdxs,
		MessageInfos:      file_server_api_internal_v1_media_proto_msgTypes,
	}.Build()
	File_server_api_internal_v1_media_proto = out.File
	file_server_api_internal_v1_media_proto_goTypes = nil
	file_server_api_internal_v1_media_proto_depIdxs = nil
}
