// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: server/api/internal/v1/progress.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateProgressRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Metadata            *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaItemId         string                 `protobuf:"bytes,3,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	LastPositionSeconds int32                  `protobuf:"varint,4,opt,name=last_position_seconds,json=lastPositionSeconds,proto3" json:"last_position_seconds,omitempty"`
	DurationSeconds     int32                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Completed           bool                   `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	CompletionSource    *string                `protobuf:"bytes,7,opt,name=completion_source,json=completionSource,proto3,oneof" json:"completion_source,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateProgressRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProgressRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *UpdateProgressRequest) GetLastPositionSeconds() int32 {
	if x != nil {
		return x.LastPositionSeconds
	}
	return 0
}

func (x *UpdateProgressRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *UpdateProgressRequest) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *UpdateProgressRequest) GetCompletionSource() string {
	if x != nil && x.CompletionSource != nil {
		return *x.CompletionSource
	}
	return ""
}

type UpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *UserMediaProgress     `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProgressResponse) GetProgress() *UserMediaProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type GetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,3,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProgressRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProgressRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

type GetUserProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Progress      *UserMediaProgress     `protobuf:"bytes,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressResponse) Reset() {
	*x = GetUserProgressResponse{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressResponse) ProtoMessage() {}

func (x *GetUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressResponse.ProtoReflect.Descriptor instead.
func (*GetUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProgressResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetUserProgressResponse) GetProgress() *UserMediaProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type BatchGetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaItemIds  []string               `protobuf:"bytes,3,rep,name=media_item_ids,json=mediaItemIds,proto3" json:"media_item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserProgressRequest) Reset() {
	*x = BatchGetUserProgressRequest{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserProgressRequest) ProtoMessage() {}

func (x *BatchGetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*BatchGetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetUserProgressRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BatchGetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchGetUserProgressRequest) GetMediaItemIds() []string {
	if x != nil {
		return x.MediaItemIds
	}
	return nil
}

type BatchGetUserProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      []*UserMediaProgress   `protobuf:"bytes,1,rep,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserProgressResponse) Reset() {
	*x = BatchGetUserProgressResponse{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserProgressResponse) ProtoMessage() {}

func (x *BatchGetUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserProgressResponse.ProtoReflect.Descriptor instead.
func (*BatchGetUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetUserProgressResponse) GetProgress() []*UserMediaProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type ListRecentUserProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IncompleteOnly bool                   `protobuf:"varint,4,opt,name=incomplete_only,json=incompleteOnly,proto3" json:"incomplete_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRecentUserProgressRequest) Reset() {
	*x = ListRecentUserProgressRequest{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecentUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecentUserProgressRequest) ProtoMessage() {}

func (x *ListRecentUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecentUserProgressRequest.ProtoReflect.Descriptor instead.
func (*ListRecentUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{6}
}

func (x *ListRecentUserProgressRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListRecentUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListRecentUserProgressRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRecentUserProgressRequest) GetIncompleteOnly() bool {
	if x != nil {
		return x.IncompleteOnly
	}
	return false
}

type ListRecentUserProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      []*UserMediaProgress   `protobuf:"bytes,1,rep,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecentUserProgressResponse) Reset() {
	*x = ListRecentUserProgressResponse{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecentUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecentUserProgressResponse) ProtoMessage() {}

func (x *ListRecentUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecentUserProgressResponse.ProtoReflect.Descriptor instead.
func (*ListRecentUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{7}
}

func (x *ListRecentUserProgressResponse) GetProgress() []*UserMediaProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type UserMediaProgress struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MediaItemId         string                 `protobuf:"bytes,1,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	LastPositionSeconds int32                  `protobuf:"varint,2,opt,name=last_position_seconds,json=lastPositionSeconds,proto3" json:"last_position_seconds,omitempty"`
	DurationSeconds     int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Completed           bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	LastWatchedAtMs     int64                  `protobuf:"varint,5,opt,name=last_watched_at_ms,json=lastWatchedAtMs,proto3" json:"last_watched_at_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserMediaProgress) Reset() {
	*x = UserMediaProgress{}
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMediaProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMediaProgress) ProtoMessage() {}

func (x *UserMediaProgress) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_progress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMediaProgress.ProtoReflect.Descriptor instead.
func (*UserMediaProgress) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_progress_proto_rawDescGZIP(), []int{8}
}

func (x *UserMediaProgress) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *UserMediaProgress) GetLastPositionSeconds() int32 {
	if x != nil {
		return x.LastPositionSeconds
	}
	return 0
}

func (x *UserMediaProgress) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *UserMediaProgress) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *UserMediaProgress) GetLastWatchedAtMs() int64 {
	if x != nil {
		return x.LastWatchedAtMs
	}
	return 0
}

var File_server_api_internal_v1_progress_proto protoreflect.FileDescriptor

const file_server_api_internal_v1_progress_proto_rawDesc = "" +
	"\n" +
	"%server/api/internal/v1/progress.proto\x12\x1awatch_together.internal.v1\x1a#server/api/internal/v1/common.proto\"\xe2\x02\n" +
	"\x15UpdateProgressRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\"\n" +
	"\rmedia_item_id\x18\x03 \x01(\tR\vmediaItemId\x122\n" +
	"\x15last_position_seconds\x18\x04 \x01(\x05R\x13lastPositionSeconds\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x05R\x0fdurationSeconds\x12\x1c\n" +
	"\tcompleted\x18\x06 \x01(\bR\tcompleted\x120\n" +
	"\x11completion_source\x18\a \x01(\tH\x00R\x10completionSource\x88\x01\x01B\x14\n" +
	"\x12_completion_source\"c\n" +
	"\x16UpdateProgressResponse\x12I\n" +
	"\bprogress\x18\x01 \x01(\v2-.watch_together.internal.v1.UserMediaProgressR\bprogress\"\x9e\x01\n" +
	"\x16GetUserProgressRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\"\n" +
	"\rmedia_item_id\x18\x03 \x01(\tR\vmediaItemId\"z\n" +
	"\x17GetUserProgressResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12I\n" +
	"\bprogress\x18\x02 \x01(\v2-.watch_together.internal.v1.UserMediaProgressR\bprogress\"\xa5\x01\n" +
	"\x1bBatchGetUserProgressRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0emedia_item_ids\x18\x03 \x03(\tR\fmediaItemIds\"i\n" +
	"\x1cBatchGetUserProgressResponse\x12I\n" +
	"\bprogress\x18\x01 \x03(\v2-.watch_together.internal.v1.UserMediaProgressR\bprogress\"\xc0\x01\n" +
	"\x1dListRecentUserProgressRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12'\n" +
	"\x0fincomplete_only\x18\x04 \x01(\bR\x0eincompleteOnly\"k\n" +
	"\x1eListRecentUserProgressResponse\x12I\n" +
	"\bprogress\x18\x01 \x03(\v2-.watch_together.internal.v1.UserMediaProgressR\bprogress\"\xe1\x01\n" +
	"\x11UserMediaProgress\x12\"\n" +
	"\rmedia_item_id\x18\x01 \x01(\tR\vmediaItemId\x122\n" +
	"\x15last_position_seconds\x18\x02 \x01(\x05R\x13lastPositionSeconds\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\x12+\n" +
	"\x12last_watched_at_ms\x18\x05 \x01(\x03R\x0flastWatchedAtMs2\xac\x04\n" +
	"\x17ProgressInternalService\x12w\n" +
	"\x0eUpdateProgress\x121.watch_together.internal.v1.UpdateProgressRequest\x1a2.watch_together.internal.v1.UpdateProgressResponse\x12z\n" +
	"\x0fGetUserProgress\x122.watch_together.internal.v1.GetUserProgressRequest\x1a3.watch_together.internal.v1.GetUserProgressResponse\x12\x89\x01\n" +
	"\x14BatchGetUserProgress\x127.watch_together.internal.v1.BatchGetUserProgressRequest\x1a8.watch_together.internal.v1.BatchGetUserProgressResponse\x12\x8f\x01\n" +
	"\x16ListRecentUserProgress\x129.watch_together.internal.v1.ListRecentUserProgressRequest\x1a:.watch_together.internal.v1.ListRecentUserProgressResponseB5Z3watch_together/server/internal/rpcgen/v1;internalv1b\x06proto3"

var (
	file_server_api_internal_v1_progress_proto_rawDescOnce sync.Once
	file_server_api_internal_v1_progress_proto_rawDescData []byte
)

func file_server_api_internal_v1_progress_proto_rawDescGZIP() []byte {
	file_server_api_internal_v1_progress_proto_rawDescOnce.Do(func() {
		file_server_api_internal_v1_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_progress_proto_rawDesc), len(file_server_api_internal_v1_progress_proto_rawDesc)))
	})
	return file_server_api_internal_v1_progress_proto_rawDescData
}

var file_server_api_internal_v1_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_server_api_internal_v1_progress_proto_goTypes = []any{
	(*UpdateProgressRequest)(nil),          // 0: watch_together.internal.v1.UpdateProgressRequest
	(*UpdateProgressResponse)(nil),         // 1: watch_together.internal.v1.UpdateProgressResponse
	(*GetUserProgressRequest)(nil),         // 2: watch_together.internal.v1.GetUserProgressRequest
	(*GetUserProgressResponse)(nil),        // 3: watch_together.internal.v1.GetUserProgressResponse
	(*BatchGetUserProgressRequest)(nil),    // 4: watch_together.internal.v1.BatchGetUserProgressRequest
	(*BatchGetUserProgressResponse)(nil),   // 5: watch_together.internal.v1.BatchGetUserProgressResponse
	(*ListRecentUserProgressRequest)(nil),  // 6: watch_together.internal.v1.ListRecentUserProgressRequest
	(*ListRecentUserProgressResponse)(nil), // 7: watch_together.internal.v1.ListRecentUserProgressResponse
	(*UserMediaProgress)(nil),              // 8: watch_together.internal.v1.UserMediaProgress
	(*RequestMetadata)(nil),                // 9: watch_together.internal.v1.RequestMetadata
}
var file_server_api_internal_v1_progress_proto_depIdxs = []int32{
	9,  // 0: watch_together.internal.v1.UpdateProgressRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	8,  // 1: watch_together.internal.v1.UpdateProgressResponse.progress:type_name -> watch_together.internal.v1.UserMediaProgress
	9,  // 2: watch_together.internal.v1.GetUserProgressRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	8,  // 3: watch_together.internal.v1.GetUserProgressResponse.progress:type_name -> watch_together.internal.v1.UserMediaProgress
	9,  // 4: watch_together.internal.v1.BatchGetUserProgressRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	8,  // 5: watch_together.internal.v1.BatchGetUserProgressResponse.progress:type_name -> watch_together.internal.v1.UserMediaProgress
	9,  // 6: watch_together.internal.v1.ListRecentUserProgressRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	8,  // 7: watch_together.internal.v1.ListRecentUserProgressResponse.progress:type_name -> watch_together.internal.v1.UserMediaProgress
	0,  // 8: watch_together.internal.v1.ProgressInternalService.UpdateProgress:input_type -> watch_together.internal.v1.UpdateProgressRequest
	2,  // 9: watch_together.internal.v1.ProgressInternalService.GetUserProgress:input_type -> watch_together.internal.v1.GetUserProgressRequest
	4,  // 10: watch_together.internal.v1.ProgressInternalService.BatchGetUserProgress:input_type -> watch_together.internal.v1.BatchGetUserProgressRequest
	6,  // 11: watch_together.internal.v1.ProgressInternalService.ListRecentUserProgress:input_type -> watch_together.internal.v1.ListRecentUserProgressRequest
	1,  // 12: watch_together.internal.v1.ProgressInternalService.UpdateProgress:output_type -> watch_together.internal.v1.UpdateProgressResponse
	3,  // 13: watch_together.internal.v1.ProgressInternalService.GetUserProgress:output_type -> watch_together.internal.v1.GetUserProgressResponse
	5,  // 14: watch_together.internal.v1.ProgressInternalService.BatchGetUserProgress:output_type -> watch_together.internal.v1.BatchGetUserProgressResponse
	7,  // 15: watch_together.internal.v1.ProgressInternalService.ListRecentUserProgress:output_type -> watch_together.internal.v1.ListRecentUserProgressResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_server_api_internal_v1_progress_proto_init() }
func file_server_api_internal_v1_progress_proto_init() {
	if File_server_api_internal_v1_progress_proto != nil {
		return
	}
	file_server_api_internal_v1_common_proto_init()
	file_server_api_internal_v1_progress_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_progress_proto_rawDesc), len(file_server_api_internal_v1_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_internal_v1_progress_proto_goTypes,
		DependencyIndexes: file_server_api_internal_v1_progress_proto_depIdxs,
		MessageInfos:      file_server_api_internal_v1_progress_proto_msgTypes,
	}.Build()
	File_server_api_internal_v1_progress_proto = out.File
	file_server_api_internal_v1_progress_proto_goTypes = nil
	file_server_api_internal_v1_progress_proto_depIdxs = nil
}
