// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: server/api/internal/v1/room.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	HostUserId    string                 `protobuf:"bytes,2,opt,name=host_user_id,json=hostUserId,proto3" json:"host_user_id,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,3,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateRoomRequest) GetHostUserId() string {
	if x != nil {
		return x.HostUserId
	}
	return ""
}

func (x *CreateRoomRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomBusinessRoom      `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Media         *RoomBusinessMedia     `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetRoom() *RoomBusinessRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *CreateRoomResponse) GetMedia() *RoomBusinessMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *JoinRoomRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomBusinessRoom      `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Media         *RoomBusinessMedia     `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	Member        *RoomBusinessMember    `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoomResponse) GetRoom() *RoomBusinessRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *JoinRoomResponse) GetMedia() *RoomBusinessMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *JoinRoomResponse) GetMember() *RoomBusinessMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveRoomRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LeaveRoomRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *LeaveRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          bool                   `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRoomResponse) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

type GetRoomDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomDetailRequest) Reset() {
	*x = GetRoomDetailRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomDetailRequest) ProtoMessage() {}

func (x *GetRoomDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomDetailRequest.ProtoReflect.Descriptor instead.
func (*GetRoomDetailRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoomDetailRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetRoomDetailRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

type GetRoomDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomBusinessRoom      `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Media         *RoomBusinessMedia     `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	Members       []*RoomBusinessMember  `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomDetailResponse) Reset() {
	*x = GetRoomDetailResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomDetailResponse) ProtoMessage() {}

func (x *GetRoomDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomDetailResponse.ProtoReflect.Descriptor instead.
func (*GetRoomDetailResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomDetailResponse) GetRoom() *RoomBusinessRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetRoomDetailResponse) GetMedia() *RoomBusinessMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *GetRoomDetailResponse) GetMembers() []*RoomBusinessMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type IsActiveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsActiveMemberRequest) Reset() {
	*x = IsActiveMemberRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsActiveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsActiveMemberRequest) ProtoMessage() {}

func (x *IsActiveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsActiveMemberRequest.ProtoReflect.Descriptor instead.
func (*IsActiveMemberRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *IsActiveMemberRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IsActiveMemberRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *IsActiveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsActiveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsActiveMemberResponse) Reset() {
	*x = IsActiveMemberResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsActiveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsActiveMemberResponse) ProtoMessage() {}

func (x *IsActiveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsActiveMemberResponse.ProtoReflect.Descriptor instead.
func (*IsActiveMemberResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *IsActiveMemberResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type RoomBusinessRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	HostUserId    string                 `protobuf:"bytes,3,opt,name=host_user_id,json=hostUserId,proto3" json:"host_user_id,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,4,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBusinessRoom) Reset() {
	*x = RoomBusinessRoom{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBusinessRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBusinessRoom) ProtoMessage() {}

func (x *RoomBusinessRoom) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBusinessRoom.ProtoReflect.Descriptor instead.
func (*RoomBusinessRoom) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *RoomBusinessRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomBusinessRoom) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomBusinessRoom) GetHostUserId() string {
	if x != nil {
		return x.HostUserId
	}
	return ""
}

func (x *RoomBusinessRoom) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *RoomBusinessRoom) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RoomBusinessMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      *string                `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,4,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	DurationMs    *int64                 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	SeasonLabel   *string                `protobuf:"bytes,6,opt,name=season_label,json=seasonLabel,proto3,oneof" json:"season_label,omitempty"`
	EpisodeLabel  *string                `protobuf:"bytes,7,opt,name=episode_label,json=episodeLabel,proto3,oneof" json:"episode_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBusinessMedia) Reset() {
	*x = RoomBusinessMedia{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBusinessMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBusinessMedia) ProtoMessage() {}

func (x *RoomBusinessMedia) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBusinessMedia.ProtoReflect.Descriptor instead.
func (*RoomBusinessMedia) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{11}
}

func (x *RoomBusinessMedia) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomBusinessMedia) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomBusinessMedia) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *RoomBusinessMedia) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *RoomBusinessMedia) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *RoomBusinessMedia) GetSeasonLabel() string {
	if x != nil && x.SeasonLabel != nil {
		return *x.SeasonLabel
	}
	return ""
}

func (x *RoomBusinessMedia) GetEpisodeLabel() string {
	if x != nil && x.EpisodeLabel != nil {
		return *x.EpisodeLabel
	}
	return ""
}

type RoomBusinessMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarSeed    string                 `protobuf:"bytes,3,opt,name=avatar_seed,json=avatarSeed,proto3" json:"avatar_seed,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBusinessMember) Reset() {
	*x = RoomBusinessMember{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBusinessMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBusinessMember) ProtoMessage() {}

func (x *RoomBusinessMember) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBusinessMember.ProtoReflect.Descriptor instead.
func (*RoomBusinessMember) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{12}
}

func (x *RoomBusinessMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomBusinessMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoomBusinessMember) GetAvatarSeed() string {
	if x != nil {
		return x.AvatarSeed
	}
	return ""
}

func (x *RoomBusinessMember) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *RoomBusinessMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_server_api_internal_v1_room_proto protoreflect.FileDescriptor

const file_server_api_internal_v1_room_proto_rawDesc = "" +
	"\n" +
	"!server/api/internal/v1/room.proto\x12\x1awatch_together.internal.v1\x1a#server/api/internal/v1/common.proto\"\xa2\x01\n" +
	"\x11CreateRoomRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12 \n" +
	"\fhost_user_id\x18\x02 \x01(\tR\n" +
	"hostUserId\x12\"\n" +
	"\rmedia_item_id\x18\x03 \x01(\tR\vmediaItemId\"\x9b\x01\n" +
	"\x12CreateRoomResponse\x12@\n" +
	"\x04room\x18\x01 \x01(\v2,.watch_together.internal.v1.RoomBusinessRoomR\x04room\x12C\n" +
	"\x05media\x18\x02 \x01(\v2-.watch_together.internal.v1.RoomBusinessMediaR\x05media\"\x90\x01\n" +
	"\x0fJoinRoomRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xe1\x01\n" +
	"\x10JoinRoomResponse\x12@\n" +
	"\x04room\x18\x01 \x01(\v2,.watch_together.internal.v1.RoomBusinessRoomR\x04room\x12C\n" +
	"\x05media\x18\x02 \x01(\v2-.watch_together.internal.v1.RoomBusinessMediaR\x05media\x12F\n" +
	"\x06member\x18\x03 \x01(\v2..watch_together.internal.v1.RoomBusinessMemberR\x06member\"\x91\x01\n" +
	"\x10LeaveRoomRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"'\n" +
	"\x11LeaveRoomResponse\x12\x12\n" +
	"\x04left\x18\x01 \x01(\bR\x04left\"|\n" +
	"\x14GetRoomDetailRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\"\xe8\x01\n" +
	"\x15GetRoomDetailResponse\x12@\n" +
	"\x04room\x18\x01 \x01(\v2,.watch_together.internal.v1.RoomBusinessRoomR\x04room\x12C\n" +
	"\x05media\x18\x02 \x01(\v2-.watch_together.internal.v1.RoomBusinessMediaR\x05media\x12H\n" +
	"\amembers\x18\x03 \x03(\v2..watch_together.internal.v1.RoomBusinessMemberR\amembers\"\x96\x01\n" +
	"\x15IsActiveMemberRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"0\n" +
	"\x16IsActiveMemberResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\"\x9d\x01\n" +
	"\x10RoomBusinessRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12 \n" +
	"\fhost_user_id\x18\x03 \x01(\tR\n" +
	"hostUserId\x12\"\n" +
	"\rmedia_item_id\x18\x04 \x01(\tR\vmediaItemId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xaf\x02\n" +
	"\x11RoomBusinessMedia\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\bsubtitle\x18\x03 \x01(\tH\x00R\bsubtitle\x88\x01\x01\x12\x1b\n" +
	"\tmedia_url\x18\x04 \x01(\tR\bmediaUrl\x12$\n" +
	"\vduration_ms\x18\x05 \x01(\x03H\x01R\n" +
	"durationMs\x88\x01\x01\x12&\n" +
	"\fseason_label\x18\x06 \x01(\tH\x02R\vseasonLabel\x88\x01\x01\x12(\n" +
	"\repisode_label\x18\a \x01(\tH\x03R\fepisodeLabel\x88\x01\x01B\v\n" +
	"\t_subtitleB\x0e\n" +
	"\f_duration_msB\x0f\n" +
	"\r_season_labelB\x10\n" +
	"\x0e_episode_label\"\xb1\x01\n" +
	"\x12RoomBusinessMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1f\n" +
	"\vavatar_seed\x18\x03 \x01(\tR\n" +
	"avatarSeed\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04roleB\r\n" +
	"\v_avatar_url2\xc2\x04\n" +
	"\x13RoomInternalService\x12k\n" +
	"\n" +
	"CreateRoom\x12-.watch_together.internal.v1.CreateRoomRequest\x1a..watch_together.internal.v1.CreateRoomResponse\x12e\n" +
	"\bJoinRoom\x12+.watch_together.internal.v1.JoinRoomRequest\x1a,.watch_together.internal.v1.JoinRoomResponse\x12h\n" +
	"\tLeaveRoom\x12,.watch_together.internal.v1.LeaveRoomRequest\x1a-.watch_together.internal.v1.LeaveRoomResponse\x12t\n" +
	"\rGetRoomDetail\x120.watch_together.internal.v1.GetRoomDetailRequest\x1a1.watch_together.internal.v1.GetRoomDetailResponse\x12w\n" +
	"\x0eIsActiveMember\x121.watch_together.internal.v1.IsActiveMemberRequest\x1a2.watch_together.internal.v1.IsActiveMemberResponseB5Z3watch_together/server/internal/rpcgen/v1;internalv1b\x06proto3"

var (
	file_server_api_internal_v1_room_proto_rawDescOnce sync.Once
	file_server_api_internal_v1_room_proto_rawDescData []byte
)

func file_server_api_internal_v1_room_proto_rawDescGZIP() []byte {
	file_server_api_internal_v1_room_proto_rawDescOnce.Do(func() {
		file_server_api_internal_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_room_proto_rawDesc), len(file_server_api_internal_v1_room_proto_rawDesc)))
	})
	return file_server_api_internal_v1_room_proto_rawDescData
}

var file_server_api_internal_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_api_internal_v1_room_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),      // 0: watch_together.internal.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),     // 1: watch_together.internal.v1.CreateRoomResponse
	(*JoinRoomRequest)(nil),        // 2: watch_together.internal.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),       // 3: watch_together.internal.v1.JoinRoomResponse
	(*LeaveRoomRequest)(nil),       // 4: watch_together.internal.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),      // 5: watch_together.internal.v1.LeaveRoomResponse
	(*GetRoomDetailRequest)(nil),   // 6: watch_together.internal.v1.GetRoomDetailRequest
	(*GetRoomDetailResponse)(nil),  // 7: watch_together.internal.v1.GetRoomDetailResponse
	(*IsActiveMemberRequest)(nil),  // 8: watch_together.internal.v1.IsActiveMemberRequest
	(*IsActiveMemberResponse)(nil), // 9: watch_together.internal.v1.IsActiveMemberResponse
	(*RoomBusinessRoom)(nil),       // 10: watch_together.internal.v1.RoomBusinessRoom
	(*RoomBusinessMedia)(nil),      // 11: watch_together.internal.v1.RoomBusinessMedia
	(*RoomBusinessMember)(nil),     // 12: watch_together.internal.v1.RoomBusinessMember
	(*RequestMetadata)(nil),        // 13: watch_together.internal.v1.RequestMetadata
}
var file_server_api_internal_v1_room_proto_depIdxs = []int32{
	13, // 0: watch_together.internal.v1.CreateRoomRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	10, // 1: watch_together.internal.v1.CreateRoomResponse.room:type_name -> watch_together.internal.v1.RoomBusinessRoom
	11, // 2: watch_together.internal.v1.CreateRoomResponse.media:type_name -> watch_together.internal.v1.RoomBusinessMedia
	13, // 3: watch_together.internal.v1.JoinRoomRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	10, // 4: watch_together.internal.v1.JoinRoomResponse.room:type_name -> watch_together.internal.v1.RoomBusinessRoom
	11, // 5: watch_together.internal.v1.JoinRoomResponse.media:type_name -> watch_together.internal.v1.RoomBusinessMedia
	12, // 6: watch_together.internal.v1.JoinRoomResponse.member:type_name -> watch_together.internal.v1.RoomBusinessMember
	13, // 7: watch_together.internal.v1.LeaveRoomRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	13, // 8: watch_together.internal.v1.GetRoomDetailRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	10, // 9: watch_together.internal.v1.GetRoomDetailResponse.room:type_name -> watch_together.internal.v1.RoomBusinessRoom
	11, // 10: watch_together.internal.v1.GetRoomDetailResponse.media:type_name -> watch_together.internal.v1.RoomBusinessMedia
	12, // 11: watch_together.internal.v1.GetRoomDetailResponse.members:type_name -> watch_together.internal.v1.RoomBusinessMember
	13, // 12: watch_together.internal.v1.IsActiveMemberRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	0,  // 13: watch_together.internal.v1.RoomInternalService.CreateRoom:input_type -> watch_together.internal.v1.CreateRoomRequest
	2,  // 14: watch_together.internal.v1.RoomInternalService.JoinRoom:input_type -> watch_together.internal.v1.JoinRoomRequest
	4,  // 15: watch_together.internal.v1.RoomInternalService.LeaveRoom:input_type -> watch_together.internal.v1.LeaveRoomRequest
	6,  // 16: watch_together.internal.v1.RoomInternalService.GetRoomDetail:input_type -> watch_together.internal.v1.GetRoomDetailRequest
	8,  // 17: watch_together.internal.v1.RoomInternalService.IsActiveMember:input_type -> watch_together.internal.v1.IsActiveMemberRequest
	1,  // 18: watch_together.internal.v1.RoomInternalService.CreateRoom:output_type -> watch_together.internal.v1.CreateRoomResponse
	3,  // 19: watch_together.internal.v1.RoomInternalService.JoinRoom:output_type -> watch_together.internal.v1.JoinRoomResponse
	5,  // 20: watch_together.internal.v1.RoomInternalService.LeaveRoom:output_type -> watch_together.internal.v1.LeaveRoomResponse
	7,  // 21: watch_together.internal.v1.RoomInternalService.GetRoomDetail:output_type -> watch_together.internal.v1.GetRoomDetailResponse
	9,  // 22: watch_together.internal.v1.RoomInternalService.IsActiveMember:output_type -> watch_together.internal.v1.IsActiveMemberResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_server_api_internal_v1_room_proto_init() }
func file_server_api_internal_v1_room_proto_init() {
	if File_server_api_internal_v1_room_proto != nil {
		return
	}
	file_server_api_internal_v1_common_proto_init()
	file_server_api_internal_v1_room_proto_msgTypes[11].OneofWrappers = []any{}
	file_server_api_internal_v1_room_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_room_proto_rawDesc), len(file_server_api_internal_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_internal_v1_room_proto_goTypes,
		DependencyIndexes: file_server_api_internal_v1_room_proto_depIdxs,
		MessageInfos:      file_server_api_internal_v1_room_proto_msgTypes,
	}.Build()
	File_server_api_internal_v1_room_proto = out.File
	file_server_api_internal_v1_room_proto_goTypes = nil
	file_server_api_internal_v1_room_proto_depIdxs = nil
}
