// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: server/api/internal/v1/room.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	HostUserId    string                 `protobuf:"bytes,2,opt,name=host_user_id,json=hostUserId,proto3" json:"host_user_id,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,3,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateRoomRequest) GetHostUserId() string {
	if x != nil {
		return x.HostUserId
	}
	return ""
}

func (x *CreateRoomRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomBusinessRoom      `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Media         *RoomBusinessMedia     `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetRoom() *RoomBusinessRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *CreateRoomResponse) GetMedia() *RoomBusinessMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *JoinRoomRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomBusinessRoom      `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Media         *RoomBusinessMedia     `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	Member        *RoomBusinessMember    `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoomResponse) GetRoom() *RoomBusinessRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *JoinRoomResponse) GetMedia() *RoomBusinessMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *JoinRoomResponse) GetMember() *RoomBusinessMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveRoomRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LeaveRoomRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *LeaveRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          bool                   `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRoomResponse) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

type GetRoomDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomDetailRequest) Reset() {
	*x = GetRoomDetailRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomDetailRequest) ProtoMessage() {}

func (x *GetRoomDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomDetailRequest.ProtoReflect.Descriptor instead.
func (*GetRoomDetailRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoomDetailRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetRoomDetailRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

type GetRoomDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomBusinessRoom      `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Media         *RoomBusinessMedia     `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	Members       []*RoomBusinessMember  `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomDetailResponse) Reset() {
	*x = GetRoomDetailResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomDetailResponse) ProtoMessage() {}

func (x *GetRoomDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomDetailResponse.ProtoReflect.Descriptor instead.
func (*GetRoomDetailResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomDetailResponse) GetRoom() *RoomBusinessRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetRoomDetailResponse) GetMedia() *RoomBusinessMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *GetRoomDetailResponse) GetMembers() []*RoomBusinessMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type IsActiveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsActiveMemberRequest) Reset() {
	*x = IsActiveMemberRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsActiveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsActiveMemberRequest) ProtoMessage() {}

func (x *IsActiveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsActiveMemberRequest.ProtoReflect.Descriptor instead.
func (*IsActiveMemberRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *IsActiveMemberRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IsActiveMemberRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *IsActiveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsActiveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsActiveMemberResponse) Reset() {
	*x = IsActiveMemberResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsActiveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsActiveMemberResponse) ProtoMessage() {}

func (x *IsActiveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsActiveMemberResponse.ProtoReflect.Descriptor instead.
func (*IsActiveMemberResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *IsActiveMemberResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetRoomRuntimeBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRuntimeBootstrapRequest) Reset() {
	*x = GetRoomRuntimeBootstrapRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRuntimeBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRuntimeBootstrapRequest) ProtoMessage() {}

func (x *GetRoomRuntimeBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRuntimeBootstrapRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRuntimeBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoomRuntimeBootstrapRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetRoomRuntimeBootstrapRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

type GetRoomRuntimeBootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomBusinessRoom      `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Media         *RoomBusinessMedia     `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRuntimeBootstrapResponse) Reset() {
	*x = GetRoomRuntimeBootstrapResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRuntimeBootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRuntimeBootstrapResponse) ProtoMessage() {}

func (x *GetRoomRuntimeBootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRuntimeBootstrapResponse.ProtoReflect.Descriptor instead.
func (*GetRoomRuntimeBootstrapResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoomRuntimeBootstrapResponse) GetRoom() *RoomBusinessRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetRoomRuntimeBootstrapResponse) GetMedia() *RoomBusinessMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

type ListRecoverableRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecoverableRoomsRequest) Reset() {
	*x = ListRecoverableRoomsRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecoverableRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecoverableRoomsRequest) ProtoMessage() {}

func (x *ListRecoverableRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecoverableRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRecoverableRoomsRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{12}
}

func (x *ListRecoverableRoomsRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListRecoverableRoomsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRecoverableRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCodes     []string               `protobuf:"bytes,1,rep,name=room_codes,json=roomCodes,proto3" json:"room_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecoverableRoomsResponse) Reset() {
	*x = ListRecoverableRoomsResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecoverableRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecoverableRoomsResponse) ProtoMessage() {}

func (x *ListRecoverableRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecoverableRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRecoverableRoomsResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{13}
}

func (x *ListRecoverableRoomsResponse) GetRoomCodes() []string {
	if x != nil {
		return x.RoomCodes
	}
	return nil
}

type MarkRoomGracePeriodRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode       string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	LastEmptyAtMs  int64                  `protobuf:"varint,3,opt,name=last_empty_at_ms,json=lastEmptyAtMs,proto3" json:"last_empty_at_ms,omitempty"`
	DestroyAfterMs int64                  `protobuf:"varint,4,opt,name=destroy_after_ms,json=destroyAfterMs,proto3" json:"destroy_after_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkRoomGracePeriodRequest) Reset() {
	*x = MarkRoomGracePeriodRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRoomGracePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRoomGracePeriodRequest) ProtoMessage() {}

func (x *MarkRoomGracePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRoomGracePeriodRequest.ProtoReflect.Descriptor instead.
func (*MarkRoomGracePeriodRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{14}
}

func (x *MarkRoomGracePeriodRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MarkRoomGracePeriodRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *MarkRoomGracePeriodRequest) GetLastEmptyAtMs() int64 {
	if x != nil {
		return x.LastEmptyAtMs
	}
	return 0
}

func (x *MarkRoomGracePeriodRequest) GetDestroyAfterMs() int64 {
	if x != nil {
		return x.DestroyAfterMs
	}
	return 0
}

type MarkRoomGracePeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRoomGracePeriodResponse) Reset() {
	*x = MarkRoomGracePeriodResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRoomGracePeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRoomGracePeriodResponse) ProtoMessage() {}

func (x *MarkRoomGracePeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRoomGracePeriodResponse.ProtoReflect.Descriptor instead.
func (*MarkRoomGracePeriodResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{15}
}

func (x *MarkRoomGracePeriodResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type MarkRoomActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRoomActiveRequest) Reset() {
	*x = MarkRoomActiveRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRoomActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRoomActiveRequest) ProtoMessage() {}

func (x *MarkRoomActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRoomActiveRequest.ProtoReflect.Descriptor instead.
func (*MarkRoomActiveRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{16}
}

func (x *MarkRoomActiveRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MarkRoomActiveRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

type MarkRoomActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRoomActiveResponse) Reset() {
	*x = MarkRoomActiveResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRoomActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRoomActiveResponse) ProtoMessage() {}

func (x *MarkRoomActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRoomActiveResponse.ProtoReflect.Descriptor instead.
func (*MarkRoomActiveResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{17}
}

func (x *MarkRoomActiveResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type DestroyRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRoomRequest) Reset() {
	*x = DestroyRoomRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRoomRequest) ProtoMessage() {}

func (x *DestroyRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRoomRequest.ProtoReflect.Descriptor instead.
func (*DestroyRoomRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{18}
}

func (x *DestroyRoomRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DestroyRoomRequest) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

type DestroyRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destroyed     bool                   `protobuf:"varint,1,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRoomResponse) Reset() {
	*x = DestroyRoomResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRoomResponse) ProtoMessage() {}

func (x *DestroyRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRoomResponse.ProtoReflect.Descriptor instead.
func (*DestroyRoomResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{19}
}

func (x *DestroyRoomResponse) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

type MarkAllActiveRoomsGracePeriodRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	LastEmptyAtMs  int64                  `protobuf:"varint,2,opt,name=last_empty_at_ms,json=lastEmptyAtMs,proto3" json:"last_empty_at_ms,omitempty"`
	DestroyAfterMs int64                  `protobuf:"varint,3,opt,name=destroy_after_ms,json=destroyAfterMs,proto3" json:"destroy_after_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkAllActiveRoomsGracePeriodRequest) Reset() {
	*x = MarkAllActiveRoomsGracePeriodRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllActiveRoomsGracePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllActiveRoomsGracePeriodRequest) ProtoMessage() {}

func (x *MarkAllActiveRoomsGracePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllActiveRoomsGracePeriodRequest.ProtoReflect.Descriptor instead.
func (*MarkAllActiveRoomsGracePeriodRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{20}
}

func (x *MarkAllActiveRoomsGracePeriodRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MarkAllActiveRoomsGracePeriodRequest) GetLastEmptyAtMs() int64 {
	if x != nil {
		return x.LastEmptyAtMs
	}
	return 0
}

func (x *MarkAllActiveRoomsGracePeriodRequest) GetDestroyAfterMs() int64 {
	if x != nil {
		return x.DestroyAfterMs
	}
	return 0
}

type MarkAllActiveRoomsGracePeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int64                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllActiveRoomsGracePeriodResponse) Reset() {
	*x = MarkAllActiveRoomsGracePeriodResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllActiveRoomsGracePeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllActiveRoomsGracePeriodResponse) ProtoMessage() {}

func (x *MarkAllActiveRoomsGracePeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllActiveRoomsGracePeriodResponse.ProtoReflect.Descriptor instead.
func (*MarkAllActiveRoomsGracePeriodResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{21}
}

func (x *MarkAllActiveRoomsGracePeriodResponse) GetUpdatedCount() int64 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

type CleanupExpiredRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NowMs         int64                  `protobuf:"varint,2,opt,name=now_ms,json=nowMs,proto3" json:"now_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupExpiredRoomsRequest) Reset() {
	*x = CleanupExpiredRoomsRequest{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupExpiredRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupExpiredRoomsRequest) ProtoMessage() {}

func (x *CleanupExpiredRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupExpiredRoomsRequest.ProtoReflect.Descriptor instead.
func (*CleanupExpiredRoomsRequest) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{22}
}

func (x *CleanupExpiredRoomsRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CleanupExpiredRoomsRequest) GetNowMs() int64 {
	if x != nil {
		return x.NowMs
	}
	return 0
}

type CleanupExpiredRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCodes     []string               `protobuf:"bytes,1,rep,name=room_codes,json=roomCodes,proto3" json:"room_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupExpiredRoomsResponse) Reset() {
	*x = CleanupExpiredRoomsResponse{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupExpiredRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupExpiredRoomsResponse) ProtoMessage() {}

func (x *CleanupExpiredRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupExpiredRoomsResponse.ProtoReflect.Descriptor instead.
func (*CleanupExpiredRoomsResponse) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{23}
}

func (x *CleanupExpiredRoomsResponse) GetRoomCodes() []string {
	if x != nil {
		return x.RoomCodes
	}
	return nil
}

type RoomBusinessRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	HostUserId    string                 `protobuf:"bytes,3,opt,name=host_user_id,json=hostUserId,proto3" json:"host_user_id,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,4,opt,name=media_item_id,json=mediaItemId,proto3" json:"media_item_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBusinessRoom) Reset() {
	*x = RoomBusinessRoom{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBusinessRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBusinessRoom) ProtoMessage() {}

func (x *RoomBusinessRoom) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBusinessRoom.ProtoReflect.Descriptor instead.
func (*RoomBusinessRoom) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{24}
}

func (x *RoomBusinessRoom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomBusinessRoom) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomBusinessRoom) GetHostUserId() string {
	if x != nil {
		return x.HostUserId
	}
	return ""
}

func (x *RoomBusinessRoom) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *RoomBusinessRoom) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RoomBusinessMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      *string                `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,4,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	DurationMs    *int64                 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	SeasonLabel   *string                `protobuf:"bytes,6,opt,name=season_label,json=seasonLabel,proto3,oneof" json:"season_label,omitempty"`
	EpisodeLabel  *string                `protobuf:"bytes,7,opt,name=episode_label,json=episodeLabel,proto3,oneof" json:"episode_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBusinessMedia) Reset() {
	*x = RoomBusinessMedia{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBusinessMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBusinessMedia) ProtoMessage() {}

func (x *RoomBusinessMedia) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBusinessMedia.ProtoReflect.Descriptor instead.
func (*RoomBusinessMedia) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{25}
}

func (x *RoomBusinessMedia) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomBusinessMedia) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoomBusinessMedia) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

func (x *RoomBusinessMedia) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *RoomBusinessMedia) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *RoomBusinessMedia) GetSeasonLabel() string {
	if x != nil && x.SeasonLabel != nil {
		return *x.SeasonLabel
	}
	return ""
}

func (x *RoomBusinessMedia) GetEpisodeLabel() string {
	if x != nil && x.EpisodeLabel != nil {
		return *x.EpisodeLabel
	}
	return ""
}

type RoomBusinessMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarSeed    string                 `protobuf:"bytes,3,opt,name=avatar_seed,json=avatarSeed,proto3" json:"avatar_seed,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBusinessMember) Reset() {
	*x = RoomBusinessMember{}
	mi := &file_server_api_internal_v1_room_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBusinessMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBusinessMember) ProtoMessage() {}

func (x *RoomBusinessMember) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_internal_v1_room_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBusinessMember.ProtoReflect.Descriptor instead.
func (*RoomBusinessMember) Descriptor() ([]byte, []int) {
	return file_server_api_internal_v1_room_proto_rawDescGZIP(), []int{26}
}

func (x *RoomBusinessMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomBusinessMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoomBusinessMember) GetAvatarSeed() string {
	if x != nil {
		return x.AvatarSeed
	}
	return ""
}

func (x *RoomBusinessMember) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *RoomBusinessMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_server_api_internal_v1_room_proto protoreflect.FileDescriptor

const file_server_api_internal_v1_room_proto_rawDesc = "" +
	"\n" +
	"!server/api/internal/v1/room.proto\x12\x1awatch_together.internal.v1\x1a#server/api/internal/v1/common.proto\"\xa2\x01\n" +
	"\x11CreateRoomRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12 \n" +
	"\fhost_user_id\x18\x02 \x01(\tR\n" +
	"hostUserId\x12\"\n" +
	"\rmedia_item_id\x18\x03 \x01(\tR\vmediaItemId\"\x9b\x01\n" +
	"\x12CreateRoomResponse\x12@\n" +
	"\x04room\x18\x01 \x01(\v2,.watch_together.internal.v1.RoomBusinessRoomR\x04room\x12C\n" +
	"\x05media\x18\x02 \x01(\v2-.watch_together.internal.v1.RoomBusinessMediaR\x05media\"\x90\x01\n" +
	"\x0fJoinRoomRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xe1\x01\n" +
	"\x10JoinRoomResponse\x12@\n" +
	"\x04room\x18\x01 \x01(\v2,.watch_together.internal.v1.RoomBusinessRoomR\x04room\x12C\n" +
	"\x05media\x18\x02 \x01(\v2-.watch_together.internal.v1.RoomBusinessMediaR\x05media\x12F\n" +
	"\x06member\x18\x03 \x01(\v2..watch_together.internal.v1.RoomBusinessMemberR\x06member\"\x91\x01\n" +
	"\x10LeaveRoomRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"'\n" +
	"\x11LeaveRoomResponse\x12\x12\n" +
	"\x04left\x18\x01 \x01(\bR\x04left\"|\n" +
	"\x14GetRoomDetailRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\"\xe8\x01\n" +
	"\x15GetRoomDetailResponse\x12@\n" +
	"\x04room\x18\x01 \x01(\v2,.watch_together.internal.v1.RoomBusinessRoomR\x04room\x12C\n" +
	"\x05media\x18\x02 \x01(\v2-.watch_together.internal.v1.RoomBusinessMediaR\x05media\x12H\n" +
	"\amembers\x18\x03 \x03(\v2..watch_together.internal.v1.RoomBusinessMemberR\amembers\"\x96\x01\n" +
	"\x15IsActiveMemberRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"0\n" +
	"\x16IsActiveMemberResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\"\x86\x01\n" +
	"\x1eGetRoomRuntimeBootstrapRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\"\xa8\x01\n" +
	"\x1fGetRoomRuntimeBootstrapResponse\x12@\n" +
	"\x04room\x18\x01 \x01(\v2,.watch_together.internal.v1.RoomBusinessRoomR\x04room\x12C\n" +
	"\x05media\x18\x02 \x01(\v2-.watch_together.internal.v1.RoomBusinessMediaR\x05media\"|\n" +
	"\x1bListRecoverableRoomsRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"=\n" +
	"\x1cListRecoverableRoomsResponse\x12\x1d\n" +
	"\n" +
	"room_codes\x18\x01 \x03(\tR\troomCodes\"\xd5\x01\n" +
	"\x1aMarkRoomGracePeriodRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12'\n" +
	"\x10last_empty_at_ms\x18\x03 \x01(\x03R\rlastEmptyAtMs\x12(\n" +
	"\x10destroy_after_ms\x18\x04 \x01(\x03R\x0edestroyAfterMs\"7\n" +
	"\x1bMarkRoomGracePeriodResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"}\n" +
	"\x15MarkRoomActiveRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\"2\n" +
	"\x16MarkRoomActiveResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"z\n" +
	"\x12DestroyRoomRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\"3\n" +
	"\x13DestroyRoomResponse\x12\x1c\n" +
	"\tdestroyed\x18\x01 \x01(\bR\tdestroyed\"\xc2\x01\n" +
	"$MarkAllActiveRoomsGracePeriodRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12'\n" +
	"\x10last_empty_at_ms\x18\x02 \x01(\x03R\rlastEmptyAtMs\x12(\n" +
	"\x10destroy_after_ms\x18\x03 \x01(\x03R\x0edestroyAfterMs\"L\n" +
	"%MarkAllActiveRoomsGracePeriodResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x03R\fupdatedCount\"|\n" +
	"\x1aCleanupExpiredRoomsRequest\x12G\n" +
	"\bmetadata\x18\x01 \x01(\v2+.watch_together.internal.v1.RequestMetadataR\bmetadata\x12\x15\n" +
	"\x06now_ms\x18\x02 \x01(\x03R\x05nowMs\"<\n" +
	"\x1bCleanupExpiredRoomsResponse\x12\x1d\n" +
	"\n" +
	"room_codes\x18\x01 \x03(\tR\troomCodes\"\x9d\x01\n" +
	"\x10RoomBusinessRoom\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12 \n" +
	"\fhost_user_id\x18\x03 \x01(\tR\n" +
	"hostUserId\x12\"\n" +
	"\rmedia_item_id\x18\x04 \x01(\tR\vmediaItemId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xaf\x02\n" +
	"\x11RoomBusinessMedia\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\bsubtitle\x18\x03 \x01(\tH\x00R\bsubtitle\x88\x01\x01\x12\x1b\n" +
	"\tmedia_url\x18\x04 \x01(\tR\bmediaUrl\x12$\n" +
	"\vduration_ms\x18\x05 \x01(\x03H\x01R\n" +
	"durationMs\x88\x01\x01\x12&\n" +
	"\fseason_label\x18\x06 \x01(\tH\x02R\vseasonLabel\x88\x01\x01\x12(\n" +
	"\repisode_label\x18\a \x01(\tH\x03R\fepisodeLabel\x88\x01\x01B\v\n" +
	"\t_subtitleB\x0e\n" +
	"\f_duration_msB\x0f\n" +
	"\r_season_labelB\x10\n" +
	"\x0e_episode_label\"\xb1\x01\n" +
	"\x12RoomBusinessMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1f\n" +
	"\vavatar_seed\x18\x03 \x01(\tR\n" +
	"avatarSeed\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04roleB\r\n" +
	"\v_avatar_url2\x85\f\n" +
	"\x13RoomInternalService\x12k\n" +
	"\n" +
	"CreateRoom\x12-.watch_together.internal.v1.CreateRoomRequest\x1a..watch_together.internal.v1.CreateRoomResponse\x12e\n" +
	"\bJoinRoom\x12+.watch_together.internal.v1.JoinRoomRequest\x1a,.watch_together.internal.v1.JoinRoomResponse\x12h\n" +
	"\tLeaveRoom\x12,.watch_together.internal.v1.LeaveRoomRequest\x1a-.watch_together.internal.v1.LeaveRoomResponse\x12t\n" +
	"\rGetRoomDetail\x120.watch_together.internal.v1.GetRoomDetailRequest\x1a1.watch_together.internal.v1.GetRoomDetailResponse\x12w\n" +
	"\x0eIsActiveMember\x121.watch_together.internal.v1.IsActiveMemberRequest\x1a2.watch_together.internal.v1.IsActiveMemberResponse\x12\x92\x01\n" +
	"\x17GetRoomRuntimeBootstrap\x12:.watch_together.internal.v1.GetRoomRuntimeBootstrapRequest\x1a;.watch_together.internal.v1.GetRoomRuntimeBootstrapResponse\x12\x89\x01\n" +
	"\x14ListRecoverableRooms\x127.watch_together.internal.v1.ListRecoverableRoomsRequest\x1a8.watch_together.internal.v1.ListRecoverableRoomsResponse\x12\x86\x01\n" +
	"\x13MarkRoomGracePeriod\x126.watch_together.internal.v1.MarkRoomGracePeriodRequest\x1a7.watch_together.internal.v1.MarkRoomGracePeriodResponse\x12w\n" +
	"\x0eMarkRoomActive\x121.watch_together.internal.v1.MarkRoomActiveRequest\x1a2.watch_together.internal.v1.MarkRoomActiveResponse\x12n\n" +
	"\vDestroyRoom\x12..watch_together.internal.v1.DestroyRoomRequest\x1a/.watch_together.internal.v1.DestroyRoomResponse\x12\xa4\x01\n" +
	"\x1dMarkAllActiveRoomsGracePeriod\x12@.watch_together.internal.v1.MarkAllActiveRoomsGracePeriodRequest\x1aA.watch_together.internal.v1.MarkAllActiveRoomsGracePeriodResponse\x12\x86\x01\n" +
	"\x13CleanupExpiredRooms\x126.watch_together.internal.v1.CleanupExpiredRoomsRequest\x1a7.watch_together.internal.v1.CleanupExpiredRoomsResponseB5Z3watch_together/server/internal/rpcgen/v1;internalv1b\x06proto3"

var (
	file_server_api_internal_v1_room_proto_rawDescOnce sync.Once
	file_server_api_internal_v1_room_proto_rawDescData []byte
)

func file_server_api_internal_v1_room_proto_rawDescGZIP() []byte {
	file_server_api_internal_v1_room_proto_rawDescOnce.Do(func() {
		file_server_api_internal_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_room_proto_rawDesc), len(file_server_api_internal_v1_room_proto_rawDesc)))
	})
	return file_server_api_internal_v1_room_proto_rawDescData
}

var file_server_api_internal_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_server_api_internal_v1_room_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),                     // 0: watch_together.internal.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),                    // 1: watch_together.internal.v1.CreateRoomResponse
	(*JoinRoomRequest)(nil),                       // 2: watch_together.internal.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),                      // 3: watch_together.internal.v1.JoinRoomResponse
	(*LeaveRoomRequest)(nil),                      // 4: watch_together.internal.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),                     // 5: watch_together.internal.v1.LeaveRoomResponse
	(*GetRoomDetailRequest)(nil),                  // 6: watch_together.internal.v1.GetRoomDetailRequest
	(*GetRoomDetailResponse)(nil),                 // 7: watch_together.internal.v1.GetRoomDetailResponse
	(*IsActiveMemberRequest)(nil),                 // 8: watch_together.internal.v1.IsActiveMemberRequest
	(*IsActiveMemberResponse)(nil),                // 9: watch_together.internal.v1.IsActiveMemberResponse
	(*GetRoomRuntimeBootstrapRequest)(nil),        // 10: watch_together.internal.v1.GetRoomRuntimeBootstrapRequest
	(*GetRoomRuntimeBootstrapResponse)(nil),       // 11: watch_together.internal.v1.GetRoomRuntimeBootstrapResponse
	(*ListRecoverableRoomsRequest)(nil),           // 12: watch_together.internal.v1.ListRecoverableRoomsRequest
	(*ListRecoverableRoomsResponse)(nil),          // 13: watch_together.internal.v1.ListRecoverableRoomsResponse
	(*MarkRoomGracePeriodRequest)(nil),            // 14: watch_together.internal.v1.MarkRoomGracePeriodRequest
	(*MarkRoomGracePeriodResponse)(nil),           // 15: watch_together.internal.v1.MarkRoomGracePeriodResponse
	(*MarkRoomActiveRequest)(nil),                 // 16: watch_together.internal.v1.MarkRoomActiveRequest
	(*MarkRoomActiveResponse)(nil),                // 17: watch_together.internal.v1.MarkRoomActiveResponse
	(*DestroyRoomRequest)(nil),                    // 18: watch_together.internal.v1.DestroyRoomRequest
	(*DestroyRoomResponse)(nil),                   // 19: watch_together.internal.v1.DestroyRoomResponse
	(*MarkAllActiveRoomsGracePeriodRequest)(nil),  // 20: watch_together.internal.v1.MarkAllActiveRoomsGracePeriodRequest
	(*MarkAllActiveRoomsGracePeriodResponse)(nil), // 21: watch_together.internal.v1.MarkAllActiveRoomsGracePeriodResponse
	(*CleanupExpiredRoomsRequest)(nil),            // 22: watch_together.internal.v1.CleanupExpiredRoomsRequest
	(*CleanupExpiredRoomsResponse)(nil),           // 23: watch_together.internal.v1.CleanupExpiredRoomsResponse
	(*RoomBusinessRoom)(nil),                      // 24: watch_together.internal.v1.RoomBusinessRoom
	(*RoomBusinessMedia)(nil),                     // 25: watch_together.internal.v1.RoomBusinessMedia
	(*RoomBusinessMember)(nil),                    // 26: watch_together.internal.v1.RoomBusinessMember
	(*RequestMetadata)(nil),                       // 27: watch_together.internal.v1.RequestMetadata
}
var file_server_api_internal_v1_room_proto_depIdxs = []int32{
	27, // 0: watch_together.internal.v1.CreateRoomRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	24, // 1: watch_together.internal.v1.CreateRoomResponse.room:type_name -> watch_together.internal.v1.RoomBusinessRoom
	25, // 2: watch_together.internal.v1.CreateRoomResponse.media:type_name -> watch_together.internal.v1.RoomBusinessMedia
	27, // 3: watch_together.internal.v1.JoinRoomRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	24, // 4: watch_together.internal.v1.JoinRoomResponse.room:type_name -> watch_together.internal.v1.RoomBusinessRoom
	25, // 5: watch_together.internal.v1.JoinRoomResponse.media:type_name -> watch_together.internal.v1.RoomBusinessMedia
	26, // 6: watch_together.internal.v1.JoinRoomResponse.member:type_name -> watch_together.internal.v1.RoomBusinessMember
	27, // 7: watch_together.internal.v1.LeaveRoomRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	27, // 8: watch_together.internal.v1.GetRoomDetailRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	24, // 9: watch_together.internal.v1.GetRoomDetailResponse.room:type_name -> watch_together.internal.v1.RoomBusinessRoom
	25, // 10: watch_together.internal.v1.GetRoomDetailResponse.media:type_name -> watch_together.internal.v1.RoomBusinessMedia
	26, // 11: watch_together.internal.v1.GetRoomDetailResponse.members:type_name -> watch_together.internal.v1.RoomBusinessMember
	27, // 12: watch_together.internal.v1.IsActiveMemberRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	27, // 13: watch_together.internal.v1.GetRoomRuntimeBootstrapRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	24, // 14: watch_together.internal.v1.GetRoomRuntimeBootstrapResponse.room:type_name -> watch_together.internal.v1.RoomBusinessRoom
	25, // 15: watch_together.internal.v1.GetRoomRuntimeBootstrapResponse.media:type_name -> watch_together.internal.v1.RoomBusinessMedia
	27, // 16: watch_together.internal.v1.ListRecoverableRoomsRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	27, // 17: watch_together.internal.v1.MarkRoomGracePeriodRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	27, // 18: watch_together.internal.v1.MarkRoomActiveRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	27, // 19: watch_together.internal.v1.DestroyRoomRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	27, // 20: watch_together.internal.v1.MarkAllActiveRoomsGracePeriodRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	27, // 21: watch_together.internal.v1.CleanupExpiredRoomsRequest.metadata:type_name -> watch_together.internal.v1.RequestMetadata
	0,  // 22: watch_together.internal.v1.RoomInternalService.CreateRoom:input_type -> watch_together.internal.v1.CreateRoomRequest
	2,  // 23: watch_together.internal.v1.RoomInternalService.JoinRoom:input_type -> watch_together.internal.v1.JoinRoomRequest
	4,  // 24: watch_together.internal.v1.RoomInternalService.LeaveRoom:input_type -> watch_together.internal.v1.LeaveRoomRequest
	6,  // 25: watch_together.internal.v1.RoomInternalService.GetRoomDetail:input_type -> watch_together.internal.v1.GetRoomDetailRequest
	8,  // 26: watch_together.internal.v1.RoomInternalService.IsActiveMember:input_type -> watch_together.internal.v1.IsActiveMemberRequest
	10, // 27: watch_together.internal.v1.RoomInternalService.GetRoomRuntimeBootstrap:input_type -> watch_together.internal.v1.GetRoomRuntimeBootstrapRequest
	12, // 28: watch_together.internal.v1.RoomInternalService.ListRecoverableRooms:input_type -> watch_together.internal.v1.ListRecoverableRoomsRequest
	14, // 29: watch_together.internal.v1.RoomInternalService.MarkRoomGracePeriod:input_type -> watch_together.internal.v1.MarkRoomGracePeriodRequest
	16, // 30: watch_together.internal.v1.RoomInternalService.MarkRoomActive:input_type -> watch_together.internal.v1.MarkRoomActiveRequest
	18, // 31: watch_together.internal.v1.RoomInternalService.DestroyRoom:input_type -> watch_together.internal.v1.DestroyRoomRequest
	20, // 32: watch_together.internal.v1.RoomInternalService.MarkAllActiveRoomsGracePeriod:input_type -> watch_together.internal.v1.MarkAllActiveRoomsGracePeriodRequest
	22, // 33: watch_together.internal.v1.RoomInternalService.CleanupExpiredRooms:input_type -> watch_together.internal.v1.CleanupExpiredRoomsRequest
	1,  // 34: watch_together.internal.v1.RoomInternalService.CreateRoom:output_type -> watch_together.internal.v1.CreateRoomResponse
	3,  // 35: watch_together.internal.v1.RoomInternalService.JoinRoom:output_type -> watch_together.internal.v1.JoinRoomResponse
	5,  // 36: watch_together.internal.v1.RoomInternalService.LeaveRoom:output_type -> watch_together.internal.v1.LeaveRoomResponse
	7,  // 37: watch_together.internal.v1.RoomInternalService.GetRoomDetail:output_type -> watch_together.internal.v1.GetRoomDetailResponse
	9,  // 38: watch_together.internal.v1.RoomInternalService.IsActiveMember:output_type -> watch_together.internal.v1.IsActiveMemberResponse
	11, // 39: watch_together.internal.v1.RoomInternalService.GetRoomRuntimeBootstrap:output_type -> watch_together.internal.v1.GetRoomRuntimeBootstrapResponse
	13, // 40: watch_together.internal.v1.RoomInternalService.ListRecoverableRooms:output_type -> watch_together.internal.v1.ListRecoverableRoomsResponse
	15, // 41: watch_together.internal.v1.RoomInternalService.MarkRoomGracePeriod:output_type -> watch_together.internal.v1.MarkRoomGracePeriodResponse
	17, // 42: watch_together.internal.v1.RoomInternalService.MarkRoomActive:output_type -> watch_together.internal.v1.MarkRoomActiveResponse
	19, // 43: watch_together.internal.v1.RoomInternalService.DestroyRoom:output_type -> watch_together.internal.v1.DestroyRoomResponse
	21, // 44: watch_together.internal.v1.RoomInternalService.MarkAllActiveRoomsGracePeriod:output_type -> watch_together.internal.v1.MarkAllActiveRoomsGracePeriodResponse
	23, // 45: watch_together.internal.v1.RoomInternalService.CleanupExpiredRooms:output_type -> watch_together.internal.v1.CleanupExpiredRoomsResponse
	34, // [34:46] is the sub-list for method output_type
	22, // [22:34] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_server_api_internal_v1_room_proto_init() }
func file_server_api_internal_v1_room_proto_init() {
	if File_server_api_internal_v1_room_proto != nil {
		return
	}
	file_server_api_internal_v1_common_proto_init()
	file_server_api_internal_v1_room_proto_msgTypes[25].OneofWrappers = []any{}
	file_server_api_internal_v1_room_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_internal_v1_room_proto_rawDesc), len(file_server_api_internal_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_internal_v1_room_proto_goTypes,
		DependencyIndexes: file_server_api_internal_v1_room_proto_depIdxs,
		MessageInfos:      file_server_api_internal_v1_room_proto_msgTypes,
	}.Build()
	File_server_api_internal_v1_room_proto = out.File
	file_server_api_internal_v1_room_proto_goTypes = nil
	file_server_api_internal_v1_room_proto_depIdxs = nil
}
