apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: watch-together
resources:
  - namespace.yaml
  - infra.yaml
  - postgres-init-job.yaml
  - migration-jobs.yaml
  - media-seed.yaml
  - apps.yaml
  - workers.yaml
  - nginx.yaml
